#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Terry_018_Hall_UI

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

}

