#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AudioBP_River_Emitter

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AudioBP_River_Emitter.AudioBP_River_Emitter_C
// 0x0010 (0x0380 - 0x0370)
class AAudioBP_River_Emitter_C final : public AActor
{
public:
	class UGameAudioRiverEmitter*                 GameAudioRiverEmitter;                             // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AudioBP_River_Emitter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AudioBP_River_Emitter_C")
	}
	static class AAudioBP_River_Emitter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAudioBP_River_Emitter_C>();
	}
};
DUMPER7_ASSERTS_AAudioBP_River_Emitter_C;

}

