#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GPCameraModifier_RedeployEffec

#include "Basic.hpp"

#include "DFMGameplay_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GPCameraModifier_RedeployEffec.BP_GPCameraModifier_RedeployEffec_C
// 0x0000 (0x00D0 - 0x00D0)
class UBP_GPCameraModifier_RedeployEffec_C final : public UGPCameraModifier_RedeployEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GPCameraModifier_RedeployEffec_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GPCameraModifier_RedeployEffec_C")
	}
	static class UBP_GPCameraModifier_RedeployEffec_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GPCameraModifier_RedeployEffec_C>();
	}
};
DUMPER7_ASSERTS_UBP_GPCameraModifier_RedeployEffec_C;

}

