#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameLaunchSettings

#include "Basic.hpp"

#include "DFMGameLaunch_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GameLaunchSettings.BP_GameLaunchSettings_C
// 0x0000 (0x0038 - 0x0038)
class UBP_GameLaunchSettings_C final : public UDFGameLaunchSettings
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GameLaunchSettings_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GameLaunchSettings_C")
	}
	static class UBP_GameLaunchSettings_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GameLaunchSettings_C>();
	}
};
DUMPER7_ASSERTS_UBP_GameLaunchSettings_C;

}

