#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GFStage_LobbyBHD

#include "Basic.hpp"

#include "GPGameFlow_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GFStage_LobbyBHD.BP_GFStage_LobbyBHD_C
// 0x0008 (0x0090 - 0x0088)
class UBP_GFStage_LobbyBHD_C final : public UGameFlowStage
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0088(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_GFStage_LobbyBHD(int32 EntryPoint); // (Final, UbergraphFunction) // @ 0x14B5B5E20
	void OnEndStage(); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void OnBeginStage(class UObject* Args); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void OnLuaGameFlowEvent_2B906D9B4F1B17CE8E17D8B81EDA6879(const class FString& ArgStr); // (BlueprintCallable, BlueprintEvent) // @ 0x14B5B5E20
	void OnLuaGameFlowEvent_5B6022944F3D17A5D99075BA09DFDBF7(const class FString& ArgStr); // (BlueprintCallable, BlueprintEvent) // @ 0x14B5B5E20
	void OnLuaGameFlowEvent_066D50DA4923FAB979899FAB62493E11(const class FString& ArgStr); // (BlueprintCallable, BlueprintEvent) // @ 0x14B5B5E20
	void OnLuaGameFlowEvent_707AB88F48543DDA7FC7E98B9553966B(const class FString& ArgStr); // (BlueprintCallable, BlueprintEvent) // @ 0x14B5B5E20

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GFStage_LobbyBHD_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GFStage_LobbyBHD_C")
	}
	static class UBP_GFStage_LobbyBHD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GFStage_LobbyBHD_C>();
	}
};
DUMPER7_ASSERTS_UBP_GFStage_LobbyBHD_C;

}

