#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GPTODToPerformManager

#include "Basic.hpp"

#include "DFMGameplay_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GPTODToPerformManager.BP_GPTODToPerformManager_C
// 0x0008 (0x06B0 - 0x06A8)
class ABP_GPTODToPerformManager_C final : public ADFMTODToPerformManager
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x06A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GPTODToPerformManager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GPTODToPerformManager_C")
	}
	static class ABP_GPTODToPerformManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GPTODToPerformManager_C>();
	}
};
DUMPER7_ASSERTS_ABP_GPTODToPerformManager_C;

}

