#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HallOperatorItemDisplayCtrl

#include "Basic.hpp"

#include "Hall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_HallOperatorItemDisplayCtrl.BP_HallOperatorItemDisplayCtrl_C
// 0x0008 (0x0480 - 0x0478)
class ABP_HallOperatorItemDisplayCtrl_C final : public AHallOperatorItemDisplayCtrl
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0478(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_HallOperatorItemDisplayCtrl_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_HallOperatorItemDisplayCtrl_C")
	}
	static class ABP_HallOperatorItemDisplayCtrl_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_HallOperatorItemDisplayCtrl_C>();
	}
};
DUMPER7_ASSERTS_ABP_HallOperatorItemDisplayCtrl_C;

}

