#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IntelligentSmokeBuffEntity

#include "Basic.hpp"

#include "DFMAbility_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_IntelligentSmokeBuffEntity.BP_IntelligentSmokeBuffEntity_C
// 0x0000 (0x01C0 - 0x01C0)
class UBP_IntelligentSmokeBuffEntity_C final : public USpiderMarkBuffEntity
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_IntelligentSmokeBuffEntity_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_IntelligentSmokeBuffEntity_C")
	}
	static class UBP_IntelligentSmokeBuffEntity_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_IntelligentSmokeBuffEntity_C>();
	}
};
DUMPER7_ASSERTS_UBP_IntelligentSmokeBuffEntity_C;

}

