#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Interact_HeavyMachineGun

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

}

