#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerExistFeature

#include "Basic.hpp"

#include "DFMGameplay_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PlayerExistFeature.BP_PlayerExistFeature_C
// 0x0000 (0x0088 - 0x0088)
class UBP_PlayerExistFeature_C final : public UCharacterLODFeature
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PlayerExistFeature_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PlayerExistFeature_C")
	}
	static class UBP_PlayerExistFeature_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PlayerExistFeature_C>();
	}
};
DUMPER7_ASSERTS_UBP_PlayerExistFeature_C;

}

