#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_QMarker_ShowWhenClose

#include "Basic.hpp"

#include "BP_QMarker_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_QMarker_ShowWhenClose.BP_QMarker_ShowWhenClose_C
// 0x0010 (0x0460 - 0x0450)
class ABP_QMarker_ShowWhenClose_C final : public ABP_QMarker_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_QMarker_ShowWhenClose_C;         // 0x0450(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         ShowDistanceThreshold;                             // 0x0458(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_QMarker_ShowWhenClose(int32 EntryPoint); // (Final, UbergraphFunction) // @ 0x14B5B5E20
	void ReceiveEndPlay(EEndPlayReason EndPlayReason); // (Event, Protected, BlueprintEvent) // @ 0x14B5B5E20
	void ReceiveTick(float DeltaSeconds); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void ReceiveBeginPlay(); // (Event, Protected, BlueprintEvent) // @ 0x14B5B5E20

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_QMarker_ShowWhenClose_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_QMarker_ShowWhenClose_C")
	}
	static class ABP_QMarker_ShowWhenClose_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_QMarker_ShowWhenClose_C>();
	}
};
DUMPER7_ASSERTS_ABP_QMarker_ShowWhenClose_C;

}

