#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Quest_Base

#include "Basic.hpp"

#include "GPQuest_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Quest_Base.BP_Quest_Base_C
// 0x0008 (0x04D0 - 0x04C8)
class ABP_Quest_Base_C final : public AGPQuest
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x04C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Quest_Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Quest_Base_C")
	}
	static class ABP_Quest_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Quest_Base_C>();
	}
};
DUMPER7_ASSERTS_ABP_Quest_Base_C;

}

