#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DataTableLoader

#include "Basic.hpp"

#include "DataTableLoader_structs.hpp"
#include "GPGameFlow_structs.hpp"
#include "GameCore_structs.hpp"


namespace SDK::Params
{

}

