#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ForrestTutorialSetting

#include "Basic.hpp"

#include "SOLSetting_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ForrestTutorialSetting.ForrestTutorialSetting_C
// 0x0000 (0x0408 - 0x0408)
class AForrestTutorialSetting_C final : public ASOLSetting_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ForrestTutorialSetting_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ForrestTutorialSetting_C")
	}
	static class AForrestTutorialSetting_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AForrestTutorialSetting_C>();
	}
};
DUMPER7_ASSERTS_AForrestTutorialSetting_C;

}

