#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GameModeGameplayBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DFMGameplay_structs.hpp"
#include "DFMGameplay_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GameModeGameplayBase.GameModeGameplayBase_C
// 0x0010 (0x0408 - 0x03F8)
class AGameModeGameplayBase_C : public ADFMGameModeGameplaySubsystem
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03F8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0400(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void SetCharacterEdgeLightSwitchOnLightMaterialCollectionAfter(float Value); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void SetCharacterEdgeLightStateAfter(ECharacterAmbientLightState State); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void ExecuteUbergraph_GameModeGameplayBase(int32 EntryPoint); // (Final, UbergraphFunction) // @ 0x14B5B5E20

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GameModeGameplayBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GameModeGameplayBase_C")
	}
	static class AGameModeGameplayBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGameModeGameplayBase_C>();
	}
};
DUMPER7_ASSERTS_AGameModeGameplayBase_C;

}

