#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Gamelet

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "PixUILog_structs.hpp"
#include "Gamelet_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "PixUI_classes.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// Class Gamelet.GameletPuertsUtilities
// 0x0000 (0x0028 - 0x0028)
class UGameletPuertsUtilities final : public UBlueprintFunctionLibrary
{
public:
	static void AddUserWidgetToGame(class UUserWidget* UserWidget, const class FString& PanelInfo); // (Final, Native, Static, Public) // @ 0x142482400
	static void FlushPuertsVMMessages(); // (Final, Native, Static, Public) // @ 0x142483090
	static class FString GetEngineVersion(); // (Final, Native, Static, Public) // @ 0x142483530
	static class FString GetHardwareInfo(); // (Final, Native, Static, Public) // @ 0x1424836F0
	static uint8 GetNetworkType(); // (Final, Native, Static, Public) // @ 0x142483770
	static class FString GetPlatformDesc(); // (Final, Native, Static, Public) // @ 0x1424837A0
	static class FString GetSDKVersion(); // (Final, Native, Static, Public) // @ 0x142483D20
	static class UWidgetAnimation* GetWidgetAnimationByName(class UUserWidget* Widget, const class FString& Name_0); // (Final, Native, Static, Public) // @ 0x142483DA0
	static void HelloWorld(); // (Final, Native, Static, Public) // @ 0x142483EA0
	static bool IsWithEditor(); // (Final, Native, Static, Public) // @ 0x142483770
	static class UTexture2D* LoadImageToTexture2D(const class FString& Path, ETextureGroup LODGroup, uint8 IsSRGB); // (Final, Native, Static, Public) // @ 0x142484110
	static class UUserWidget* LoadUI(const class FString& Ref, class UObject* obj); // (Final, Native, Static, Public) // @ 0x142484250
	static int32 MountPak(const class FString& PakPath); // (Final, Native, Static, Public) // @ 0x142484350
	static void ReleaseTextureResource(class UTexture2D* Texture); // (Final, Native, Static, Public) // @ 0x1424858B0
	static void RemoveUserWidgetFromGame(class UUserWidget* UserWidget, const class FString& PanelInfo); // (Final, Native, Static, Public) // @ 0x142485920
	static int32 UnMountPak(const class FString& PakPath); // (Final, Native, Static, Public) // @ 0x142486680
	static void UpdateTextureResources(class UTexture2D* Texture); // (Final, Native, Static, Public) // @ 0x142486770

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GameletPuertsUtilities")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GameletPuertsUtilities")
	}
	static class UGameletPuertsUtilities* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGameletPuertsUtilities>();
	}
};
DUMPER7_ASSERTS_UGameletPuertsUtilities;

// Class Gamelet.Gamelet
// 0x0020 (0x0048 - 0x0028)
class UGamelet final : public UObject
{
public:
	uint8                                         Pad_28[0x20];                                      // 0x0028(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UGamelet* Get(); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x142483340
	static class FString GetProductConfig(); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x142483820
	static void SetTickIntervalSec(const float TickIntervalSec); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x142486440
	static void StartTick(); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x1424864B0
	static void StopTick(); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x1424864D0

	int32 Close(); // (Final, Native, Public, BlueprintCallable) // @ 0x142482520
	void CollectPixUILogOutput(EPxLogGroups PixUILogType, EPxLogLevels PixUILogLevel, const class FString& logContent); // (Final, Native, Private) // @ 0x142482770
	int32 Deinitialize(); // (Final, Native, Public, BlueprintCallable) // @ 0x1424829C0
	int32 ExecOnRefreshUserdata(); // (Final, Native, Private) // @ 0x142482CC0
	int32 ExecOnReportData(const class FString& EventName, const class FString& Data); // (Final, Native, Private) // @ 0x142482CF0
	int32 ExecOnSDKMessage(const class FString& Msg); // (Final, Native, Private) // @ 0x142482E40
	int32 Initialize(class UGameletSettings* Settings); // (Final, Native, Public, BlueprintCallable) // @ 0x142483EC0
	int32 Open(const EGameletEnvironment Environment, const TMap<class FString, class FString>& userData); // (Final, Native, Public, HasOutParams, BlueprintCallable) // @ 0x142485010
	int32 OpenBeforeLogin(const EGameletEnvironment Environment); // (Final, Native, Public, BlueprintCallable) // @ 0x1424852B0
	int32 UpdateProductConfig(); // (Final, Native, Public, BlueprintCallable) // @ 0x142486740

	int32 AllAssetsGC() const; // (Final, Native, Public, BlueprintCallable, BlueprintPure, Const) // @ 0x1424824F0
	int32 CloseApp(const class FString& APPID) const; // (Final, Native, Public, BlueprintCallable, BlueprintPure, Const) // @ 0x142482550
	int32 CloseAppPage(const class FString& APPID, const class FString& AppPage) const; // (Final, Native, Public, BlueprintCallable, BlueprintPure, Const) // @ 0x142482620
	void EnableLog(const bool Enable) const; // (Final, Native, Public, BlueprintCallable, Const) // @ 0x142482C30
	int32 GetBackTrace(class FString* TraceInfo) const; // (Final, Native, Public, HasOutParams, BlueprintCallable, BlueprintPure, Const) // @ 0x1424833D0
	class UGameletSettings* GetGlobalSettings() const; // (Final, Native, Public, BlueprintCallable, BlueprintPure, Const) // @ 0x1424836C0
	int32 OpenApp(const class FString& APPID, const class FString& OpenArgs) const; // (Final, Native, Public, BlueprintCallable, BlueprintPure, Const) // @ 0x142485160
	int32 RefreshUserdata(const TMap<class FString, class FString>& userData) const; // (Final, Native, Public, HasOutParams, BlueprintCallable, BlueprintPure, Const) // @ 0x1424857A0
	int32 SendMessageToApp(const class FString& APPID, const class FString& Msg) const; // (Final, Native, Public, BlueprintCallable, BlueprintPure, Const) // @ 0x142485BD0
	int32 SendMessageToSdk(const class FString& Msg) const; // (Final, Native, Public, BlueprintCallable, BlueprintPure, Const) // @ 0x142485D20
	int32 SetAppPageVisibility(const class FString& APPID, const class FString& AppPage, const bool Visible) const; // (Final, Native, Public, BlueprintCallable, BlueprintPure, Const) // @ 0x142485DF0
	int32 SetAppVisibility(const class FString& APPID, const bool Visible) const; // (Final, Native, Public, BlueprintCallable, BlueprintPure, Const) // @ 0x142485F70
	int32 SetBuiltinResConfig(const class FString& ResConfig) const; // (Final, Native, Public, BlueprintCallable, BlueprintPure, Const) // @ 0x142486080
	int32 SetDefaultFont(const class FString& FontName) const; // (Final, Native, Public, BlueprintCallable, BlueprintPure, Const) // @ 0x142486150
	int32 SetFont(const class FString& FontName, const class FString& FontPath) const; // (Final, Native, Public, BlueprintCallable, BlueprintPure, Const) // @ 0x142486220
	int32 SetScriptExternalLoadDir(const class FString& ExternalLoadDir) const; // (Final, Native, Public, BlueprintCallable, BlueprintPure, Const) // @ 0x142486370
	void Tick(float fDeltaTime) const; // (Final, Native, Public, BlueprintCallable, Const) // @ 0x1424864F0

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Gamelet")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Gamelet")
	}
	static class UGamelet* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGamelet>();
	}
};
DUMPER7_ASSERTS_UGamelet;

// Class Gamelet.GameletMatBrush
// 0x0008 (0x0040 - 0x0038)
class UGameletMatBrush final : public UPixUIBrushWrapper
{
public:
	class UMaterialInstanceDynamic*               MatInstance;                                       // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GameletMatBrush")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GameletMatBrush")
	}
	static class UGameletMatBrush* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGameletMatBrush>();
	}
};
DUMPER7_ASSERTS_UGameletMatBrush;

// Class Gamelet.GameletEnvMgr
// 0x0070 (0x0098 - 0x0028)
class UGameletEnvMgr final : public UObject
{
public:
	uint8                                         Pad_28[0x70];                                      // 0x0028(0x0070)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnEnvLoaded(const class FString& URL, const int32 ErrorCode); // (Final, Native, Public) // @ 0x142484510
	int32 OnEnvToEntryMessage(const class FString& Msg); // (Final, Native, Public) // @ 0x142484960
	int32 OnEnvToGameMessage(const class FString& Msg); // (Final, Native, Public) // @ 0x142484A30

	class FString GetBackTrace() const; // (Final, Native, Public, Const) // @ 0x1424834B0
	void OnEnvInternalError(const int32 ErrorCode, const class FString& ErrorMsg) const; // (Final, Native, Public, Const) // @ 0x142484410
	int32 OnEnvRefreshUserdata() const; // (Final, Native, Public, Const) // @ 0x1424847E0
	int32 OnEnvReportData(const class FString& EventName, const class FString& Data) const; // (Final, Native, Public, Const) // @ 0x142484810

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GameletEnvMgr")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GameletEnvMgr")
	}
	static class UGameletEnvMgr* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGameletEnvMgr>();
	}
};
DUMPER7_ASSERTS_UGameletEnvMgr;

// Class Gamelet.GameletFile
// 0x0000 (0x0028 - 0x0028)
class UGameletFile final : public UBlueprintFunctionLibrary
{
public:
	static bool CreateDirectory(const class FString& Path); // (Final, Native, Static, Public) // @ 0x142482900
	static bool DeleteDirectory(const class FString& Path); // (Final, Native, Static, Public) // @ 0x1424829F0
	static bool DeleteFile(const class FString& Path); // (Final, Native, Static, Public) // @ 0x142482AB0
	static bool DirectoryExists(const class FString& Path); // (Final, Native, Static, Public) // @ 0x142482B70
	static bool FileExists(const class FString& Path); // (Final, Native, Static, Public) // @ 0x142482F10
	static int64 FileSize(const class FString& Path); // (Final, Native, Static, Public) // @ 0x142482FD0
	static class FString GetFileMd5(const class FString& Path); // (Final, Native, Static, Public) // @ 0x1424835B0
	static class FString LoadFileToString(const class FString& Path); // (Final, Native, Static, Public) // @ 0x142484000
	static struct FGameletArrayBuffer ReadFile(const class FString& Path); // (Final, Native, Static, Public) // @ 0x1424856C0
	static bool SaveStringToFile(const class FString& Path, const class FString& Content); // (Final, Native, Static, Public) // @ 0x142485A90
	static bool WriteFile(const class FString& Path, const struct FGameletArrayBuffer& ArrayBuffer); // (Final, Native, Static, Public, HasOutParams) // @ 0x1424867E0

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GameletFile")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GameletFile")
	}
	static class UGameletFile* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGameletFile>();
	}
};
DUMPER7_ASSERTS_UGameletFile;

// Class Gamelet.GameletPaths
// 0x0000 (0x0028 - 0x0028)
class UGameletPaths final : public UBlueprintFunctionLibrary
{
public:
	static class FString GameletAppArchiveRoot(const class FString& APPID); // (Final, Native, Static, Public) // @ 0x1424830B0
	static class FString GameletContentRoot(); // (Final, Native, Static, Public) // @ 0x1424831C0
	static class FString GameletFolderName(); // (Final, Native, Static, Public) // @ 0x142483240
	static class FString GameletSavedRoot(); // (Final, Native, Static, Public) // @ 0x1424832C0
	static class FString GetPuertsAppIndexPath(const class FString& AppFolderName); // (Final, Native, Static, Public) // @ 0x142483860
	static class FString GetPuertsAppNameByPakName(const class FString& PakName); // (Final, Native, Static, Public) // @ 0x142483970
	static class FString GetPuertsAppScriptPath(const class FString& AppFolderName); // (Final, Native, Static, Public) // @ 0x142483A80
	static class FString GetPuertsEntrancePath(const class FString& PakName); // (Final, Native, Static, Public) // @ 0x142483B90
	static class FString GetPuertsScriptFolderName(); // (Final, Native, Static, Public) // @ 0x142483CA0
	static class FString LaunchDir(); // (Final, Native, Static, Public) // @ 0x142483F80
	static class FString ProjectConfigDir(); // (Final, Native, Static, Public) // @ 0x142485340
	static class FString ProjectContentDir(); // (Final, Native, Static, Public) // @ 0x1424853C0
	static class FString ProjectDir(); // (Final, Native, Static, Public) // @ 0x142485440
	static class FString ProjectIntermediateDir(); // (Final, Native, Static, Public) // @ 0x1424854C0
	static class FString ProjectModsDir(); // (Final, Native, Static, Public) // @ 0x142485540
	static class FString ProjectSavedDir(); // (Final, Native, Static, Public) // @ 0x1424855C0
	static class FString ProjectUserDir(); // (Final, Native, Static, Public) // @ 0x142485640
	static class FString RootDir(); // (Final, Native, Static, Public) // @ 0x142485A10
	static class FString ToAbsolutePathForRead(const class FString& Path); // (Final, Native, Static, Public) // @ 0x142486570
	static class FString ToAbsolutePathForWrite(const class FString& Path); // (Final, Native, Static, Public) // @ 0x142486570

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GameletPaths")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GameletPaths")
	}
	static class UGameletPaths* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGameletPaths>();
	}
};
DUMPER7_ASSERTS_UGameletPaths;

// Class Gamelet.GameletPuertsEnvMgr
// 0x0060 (0x0088 - 0x0028)
class UGameletPuertsEnvMgr final : public UObject
{
public:
	TMulticastInlineDelegate<void(const class FString& Msg)> OnPostMessage;                          // 0x0028(0x0010)(ZeroConstructor, InstancedReference, NativeAccessSpecifierPublic)
	uint8                                         Pad_38[0x50];                                      // 0x0038(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UGameletPuertsEnvMgr* Get(); // (Final, Native, Static, Public) // @ 0x142483370

	void OnEnvLoaded(const class FString& URL, const bool isSuccess); // (Final, Native, Public) // @ 0x142484610
	void OnEnvMessage(const class FString& Msg); // (Final, Native, Public) // @ 0x142484720

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GameletPuertsEnvMgr")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GameletPuertsEnvMgr")
	}
	static class UGameletPuertsEnvMgr* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGameletPuertsEnvMgr>();
	}
};
DUMPER7_ASSERTS_UGameletPuertsEnvMgr;

// Class Gamelet.GameletSettings
// 0x0068 (0x0090 - 0x0028)
class UGameletSettings final : public UObject
{
public:
	TDelegate<void(const class FString& Msg)>     OnSDKMessage;                                      // 0x0028(0x0010)(Edit, ZeroConstructor, InstancedReference, NoDestructor, NativeAccessSpecifierPublic)
	TDelegate<void()>                             OnRefreshUserdata;                                 // 0x0038(0x0010)(Edit, ZeroConstructor, InstancedReference, NoDestructor, NativeAccessSpecifierPublic)
	TDelegate<void(class UWidget* Widget, const class FString& AppInfo)> OnViewCreated;              // 0x0048(0x0010)(Edit, ZeroConstructor, InstancedReference, NoDestructor, NativeAccessSpecifierPublic)
	TDelegate<void(class UWidget* Widget, const class FString& AppInfo)> OnViewAboutToDestroy;       // 0x0058(0x0010)(Edit, ZeroConstructor, InstancedReference, NoDestructor, NativeAccessSpecifierPublic)
	TDelegate<void(const class FString& EventName, const class FString& Data)> OnReportData;         // 0x0068(0x0010)(Edit, ZeroConstructor, InstancedReference, NoDestructor, NativeAccessSpecifierPublic)
	TDelegate<void(const class FString& Msg)>     OnProfileJSSDKMessage;                             // 0x0078(0x0010)(Edit, ZeroConstructor, InstancedReference, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          DisableJsErrReport;                                // 0x0088(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          DisableGetBackTrace;                               // 0x0089(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          DelayWndCallMsg;                                   // 0x008A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          SupportUseEngineFont;                              // 0x008B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          UseSRGB;                                           // 0x008C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ForbiddenSyncServerLogConf;                        // 0x008D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8E[0x2];                                       // 0x008E(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UGameletSettings* Get(); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x1424833A0

	bool IsValidSetting() const; // (Final, Native, Public, BlueprintCallable, BlueprintPure, Const) // @ 0x142483F50

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GameletSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GameletSettings")
	}
	static class UGameletSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGameletSettings>();
	}
};
DUMPER7_ASSERTS_UGameletSettings;

// Class Gamelet.GameletWidget
// 0x0028 (0x01F8 - 0x01D0)
class UGameletWidget final : public UCanvasPanel
{
public:
	uint8                                         Pad_1D0[0x28];                                     // 0x01D0(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GameletWidget")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GameletWidget")
	}
	static class UGameletWidget* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGameletWidget>();
	}
};
DUMPER7_ASSERTS_UGameletWidget;

// Class Gamelet.GameletWindow
// 0x0148 (0x0170 - 0x0028)
class UGameletWindow final : public UObject
{
public:
	uint8                                         Pad_28[0x148];                                     // 0x0028(0x0148)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnPxWidgetScriptStateDone(); // (Final, Native, Private) // @ 0x142484FD0
	void OnPxWidgetScriptStateInit(); // (Final, Native, Private) // @ 0x142484FF0

	void OnPxWidgetClose() const; // (Final, Native, Private, Const) // @ 0x142484B00
	void OnPxWidgetInternalError(const int32 ErrorCode, const class FString& ErrorMsg) const; // (Final, Native, Private, Const) // @ 0x142484B20
	void OnPxWidgetLoaded(const class FString& URL, const int32 ErrorCode) const; // (Final, Native, Private, Const) // @ 0x142484C20
	void OnPxWidgetMessage(const class FString& Msg) const; // (Final, Native, Private, Const) // @ 0x142484D20
	bool OnPxWidgetRequestOpen(const class FString& URL, const class FString& Name_0, const class FString& Features, bool bReplace) const; // (Final, Native, Private, Const) // @ 0x142484DE0

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GameletWindow")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GameletWindow")
	}
	static class UGameletWindow* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGameletWindow>();
	}
};
DUMPER7_ASSERTS_UGameletWindow;

}

