#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Killme

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Killme.GE_Killme_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_Killme_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Killme_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Killme_C")
	}
	static class UGE_Killme_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Killme_C>();
	}
};
DUMPER7_ASSERTS_UGE_Killme_C;

}

