#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GPGameFlow

#include "Basic.hpp"


namespace SDK
{

// Enum GPGameFlow.EGameFlowStageType
// NumValues: 0x0028
enum class EGameFlowStageType : uint8
{
	None                                     = 0,
	Hotfix                                   = 1,
	VersionUpdate                            = 2,
	PrecompilePSO                            = 3,
	Login                                    = 4,
	LoginToLobby                             = 5,
	Lobby                                    = 6,
	LobbyToGame                              = 7,
	LobbyBHD                                 = 8,
	LobbyBHDToGame                           = 9,
	Game                                     = 10,
	GameToLobby                              = 11,
	GameToLobbyBHD                           = 12,
	Discovery                                = 13,
	SafeHouse                                = 14,
	LoginToModeHall                          = 15,
	LoginToBattleField                       = 16,
	LoginToSafeHouse                         = 17,
	LoginToLobbyBHD                          = 18,
	SafeHouseToBattleField                   = 19,
	SafeHouseToLobbyBHD                      = 20,
	BattleFieldToSafeHouse                   = 21,
	LobbyToLobbyBHD                          = 22,
	LobbyBHDToLobby                          = 23,
	LobbyBHDToSafeHouse                      = 24,
	ModeHall                                 = 25,
	ModeHallToLobby                          = 26,
	ModeHallToSafeHouse                      = 27,
	ModeHallToLobbyBHD                       = 28,
	SafeHouseToGame                          = 29,
	GameToSafeHouse                          = 30,
	GameToGame                               = 31,
	LobbyToLogin                             = 32,
	LoginToIntro                             = 33,
	Intro                                    = 34,
	IntroToSafeHouse                         = 35,
	PostLaunch                               = 36,
	LaunchToLogin                            = 37,
	GameSettlement                           = 38,
	EGameFlowStageType_MAX                   = 39,
};

}

