#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GPQuest

#include "Basic.hpp"

#include "GPQuest_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "GPGameHud_structs.hpp"
#include "GPGlobalDefines_structs.hpp"
#include "GPTools_classes.hpp"


namespace SDK
{

// Class GPQuest.GPQuestCountdownBase
// 0x00A8 (0x0418 - 0x0370)
class AGPQuestCountdownBase final : public AActor
{
public:
	bool                                          bIsStoped;                                         // 0x0370(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsFinished;                                       // 0x0371(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_372[0x6];                                      // 0x0372(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	int64                                         StartDateTime;                                     // 0x0378(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CountdownDuration;                                 // 0x0380(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_384[0x4];                                      // 0x0384(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Title;                                             // 0x0388(0x0018)(Edit, BlueprintVisible, Net, NativeAccessSpecifierPublic)
	uint8                                         Pad_3A0[0x10];                                     // 0x03A0(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	ECountDownHUDClassType                        CountDownHUDClassType;                             // 0x03B0(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EQA_CountdownType                             CountdownType;                                     // 0x03B1(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3B2[0x6];                                      // 0x03B2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UUserWidget>                CountDownHUDClass;                                 // 0x03B8(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3C0[0x8];                                      // 0x03C0(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<ECountDownHUDClassType, TSubclassOf<class UUserWidget>> CountDownHUDMap;                    // 0x03C8(0x0050)(Edit, ZeroConstructor, UObjectWrapper, NativeAccessSpecifierPublic)

public:
	void BP_CreateCountDownHUD(bool bShowHUD); // (Event, Protected, BlueprintEvent) // @ 0x14B5B5E20
	void BP_OnServerStartCountDown(); // (Event, Protected, BlueprintEvent) // @ 0x14B5B5E20
	void BP_OnServerStopCountDown(); // (Event, Protected, BlueprintEvent) // @ 0x14B5B5E20
	void BP_RefreshCountdownType(); // (Event, Protected, BlueprintEvent) // @ 0x14B5B5E20
	int32 GetRemainingTime(); // (Final, Native, Public, BlueprintCallable) // @ 0x141006F00
	int32 GetRemainingTimeOnClient(); // (Final, BlueprintCosmetic, Native, Public, BlueprintCallable) // @ 0x141006F30
	void OnRep_CountDownHUDClassType(); // (Final, Native, Public) // @ 0x141007120
	void OnRep_CountdownType(); // (Final, Native, Public) // @ 0x141007140
	void Recountdown(int32 Duration); // (Final, Native, Public, BlueprintCallable) // @ 0x141007280

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestCountdownBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestCountdownBase")
	}
	static class AGPQuestCountdownBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGPQuestCountdownBase>();
	}
};
DUMPER7_ASSERTS_AGPQuestCountdownBase;

// Class GPQuest.GPQuestActionContext
// 0x0090 (0x0400 - 0x0370)
class AGPQuestActionContext : public AActor
{
public:
	TMap<int32, class UGPQuestObjectiveAsyncReturnActionBase*> MapObjectiveAsyncReturnActions;       // 0x0370(0x0050)(ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	int32                                         CurrentObjectiveId;                                // 0x03C0(0x0004)(Edit, Net, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FGPQuestObjectiveInfo                  RecentObjectiveInfo;                               // 0x03C4(0x0008)(Edit, Net, EditConst, NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_3CC[0x4];                                      // 0x03CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UGPQuestActionAsyncReturnActionBase*> QActions;                                     // 0x03D0(0x0010)(ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	TArray<class UGPQuestStageAsyncReturnActionBase*> QStageActions;                                 // 0x03E0(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_3F0[0x10];                                     // 0x03F0(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void GotoObjective(int32 objectiveId); // (Native, Public) // @ 0x1410003B0
	void OnJumpObjective(int32 objectiveId); // (Event, Protected, BlueprintEvent) // @ 0x14B5B5E20
	void StageGraphJumpObjective(int32 objectiveId); // (Final, Native, Public, BlueprintCallable) // @ 0x141003260

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestActionContext")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestActionContext")
	}
	static class AGPQuestActionContext* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGPQuestActionContext>();
	}
};
DUMPER7_ASSERTS_AGPQuestActionContext;

// Class GPQuest.GPQuest
// 0x00C8 (0x04C8 - 0x0400)
class AGPQuest : public AGPQuestActionContext
{
public:
	class UGPQuestRuleHelperComponent*            RuleHelper;                                        // 0x0400(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USceneComponent*                        DefaultRoot;                                       // 0x0408(0x0008)(Edit, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         QuestID;                                           // 0x0410(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_414[0x4];                                      // 0x0414(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 QuestName;                                         // 0x0418(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 QLevelBaseDir;                                     // 0x0428(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bMainQuest;                                        // 0x0438(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bPlaying;                                          // 0x0439(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_43A[0x6];                                      // 0x043A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class AGPQuestClientProxy>        ClassOfClientProxy;                                // 0x0440(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoClear, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_448[0x10];                                     // 0x0448(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	EGPQuestEndReason                             LastEndReason;                                     // 0x0458(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_459[0x7];                                      // 0x0459(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGPQuestClientProxy*                    ClientProxyActor;                                  // 0x0460(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, EditConst, IsPlainOldData, RepNotify, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TArray<class AGPQuestMarkerBase*>             ClientQuestMarkerArray;                            // 0x0468(0x0010)(ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	class AGPQuestStage*                          CurrentStage;                                      // 0x0478(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, EditConst, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         QuestStagesCount;                                  // 0x0480(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_484[0x4];                                      // 0x0484(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<TSubclassOf<class AGPQuestStage>>      CachedQuestStageClassList;                         // 0x0488(0x0010)(ZeroConstructor, Transient, UObjectWrapper, NativeAccessSpecifierPublic)
	bool                                          bWaitingPlunder;                                   // 0x0498(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_499[0x7];                                      // 0x0499(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGPQuestVolume*                         GPQuestVolume;                                     // 0x04A0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class AGPQuestMarkerBase*>             GPQuestMarkerArray;                                // 0x04A8(0x0010)(Net, ZeroConstructor, RepNotify, NativeAccessSpecifierPublic)
	class FString                                 AIJobName;                                         // 0x04B8(0x0010)(BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void BeginQuest(); // (Native, Public) // @ 0x140FFF7D0
	void BeginQuestOnClient(); // (Net, NetReliable, Native, Event, NetMulticast, Public) // @ 0x140FFF7F0
	void BreakQuest(); // (Native, Public) // @ 0x140FFF810
	void EndQuest(EGPQuestEndReason reason); // (Native, Public) // @ 0x141000070
	void EndQuestOnClient(); // (Net, NetReliable, Native, Event, NetMulticast, Public) // @ 0x1410000F0
	void GotoStage(const class FString& StageName); // (Native, Public) // @ 0x141000440
	void OnBeginQuest(); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void OnBeginQuestManually(); // (Event, Public, BlueprintCallable, BlueprintEvent) // @ 0x14B5B5E20
	void OnEndQuest(); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void OnJumpStage(const class FString& StageName, EGPQuestPlayReason reason); // (Event, Protected, BlueprintEvent) // @ 0x14B5B5E20
	void OnNewPlayerEnterVolume(class AActor* NewPlayer); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void OnPlunder(int32 TeamID); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void OnRep_ClientProxy(); // (Final, Native, Public) // @ 0x1410007B0
	void OnRep_CurrentStage(); // (Final, Native, Public) // @ 0x1410007D0
	void OnRep_GPQuestMarkerArray(); // (Final, Native, Protected) // @ 0x1410007F0
	void OnReplayQuest(); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void OnWaitingPlunder(); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void PlunderQuest(int32 TeamID); // (Native, Public) // @ 0x1410009E0
	void QuestGraphCallFunctionByName(const class FString& Function); // (Final, Native, Public, BlueprintCallable) // @ 0x141002CB0
	void QuestGraphJumpStage(const class FString& StageName, EGPQuestPlayReason reason); // (Final, Native, Public, BlueprintCallable) // @ 0x141002D70
	void ServerAcceptContractForOfflinePlayer(class ACHARACTER* CHARACTER); // (Native, Public) // @ 0x141002E70

	class FString GetStageFullName(const class FString& StageName) const; // (Final, Native, Public, BlueprintCallable, BlueprintPure, Const) // @ 0x141000290

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuest")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuest")
	}
	static class AGPQuest* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGPQuest>();
	}
};
DUMPER7_ASSERTS_AGPQuest;

// Class GPQuest.GPQuestActionAsyncReturnActionBase
// 0x0008 (0x0038 - 0x0030)
class UGPQuestActionAsyncReturnActionBase : public UBlueprintAsyncActionBase
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestActionAsyncReturnActionBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestActionAsyncReturnActionBase")
	}
	static class UGPQuestActionAsyncReturnActionBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGPQuestActionAsyncReturnActionBase>();
	}
};
DUMPER7_ASSERTS_UGPQuestActionAsyncReturnActionBase;

// Class GPQuest.GPQuestObjectiveAsyncReturnActionBase
// 0x0010 (0x0040 - 0x0030)
class UGPQuestObjectiveAsyncReturnActionBase : public UBlueprintAsyncActionBase
{
public:
	TArray<class UGPQuestActionAsyncReturnActionBase*> QActions;                                     // 0x0030(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)

public:
	void FireReturnAction(EGPQuestObjectiveAsyncReturnBranch Branch); // (Native, Public, BlueprintCallable) // @ 0x141000110

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestObjectiveAsyncReturnActionBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestObjectiveAsyncReturnActionBase")
	}
	static class UGPQuestObjectiveAsyncReturnActionBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGPQuestObjectiveAsyncReturnActionBase>();
	}
};
DUMPER7_ASSERTS_UGPQuestObjectiveAsyncReturnActionBase;

// Class GPQuest.GPQuestActionLib_Basic
// 0x0000 (0x0028 - 0x0028)
class UGPQuestActionLib_Basic : public UBlueprintFunctionLibrary
{
public:
	static void QA_ActivateMarker(class AGPQuestActionContext* QAContext, class FName QATag_TargetTag, EGPQuestActionScope Scope); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141000A70
	static class AGPQuestMarkerBase* QA_AddMarker(class AGPQuestActionContext* QAContext, TSubclassOf<class AGPQuestMarkerBase> MarkerClass, TSubclassOf<class AActor> TargetActorClass, class FName QATag_TargetTag, const struct FVector& OffsetLocation, const float DistanceThreshold, EGPQuestActionMarkerType markerType, EGPQuestActionScope Scope, bool ShowInBigMap, class FName SocketName); // (Final, Native, Static, Public, HasDefaults, BlueprintCallable) // @ 0x141000B60
	static void QA_AddMarkerOnAllActors(class AGPQuestActionContext* QAContext, TSubclassOf<class AGPQuestMarkerBase> MarkerClass, TSubclassOf<class AActor> TargetActorClass, class FName TargetTag, const struct FVector& OffsetLocation, const float DistanceThreshold, EGPQuestActionMarkerType markerType, EGPQuestActionScope Scope, bool ShowInBigMap, class FName SocketName); // (Final, Native, Static, Public, HasDefaults, BlueprintCallable) // @ 0x141000E20
	static class AGPQuestMarkerBase* QA_AddMarkerToSpecifiedTarget(class AGPQuestActionContext* QAContext, TSubclassOf<class AGPQuestMarkerBase> MarkerClass, class AActor* TargetActor, const struct FVector& OffsetLocation, const float DistanceThreshold, EGPQuestActionMarkerType markerType, class FName SocketName, bool ShowInBigMap); // (Final, Native, Static, Public, HasDefaults, BlueprintCallable) // @ 0x1410010E0
	static void QA_ClearOptionalObjective(class AGPQuestActionContext* QAContext); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141001320
	static void QA_DeactivateMarker(class AGPQuestActionContext* QAContext, class FName QATag_TargetTag, EGPQuestActionScope Scope); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141001390
	static void QA_FindAllActor(class AGPQuestActionContext* QAContext, TSubclassOf<class AActor> ActorClass, class FName Tag, const class FString& Name_0, EGPQuestActionScope Scope, TArray<class AActor*>* OutActors); // (Final, Native, Static, Public, HasOutParams, BlueprintCallable) // @ 0x141001480
	static class AActor* QA_FindFirstActor(class AGPQuestActionContext* QAContext, TSubclassOf<class AActor> ActorClass, class FName Tag, const class FString& Name_0, EGPQuestActionScope Scope); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x1410016B0
	static class UActorComponent* QA_FindFirstActorWithComponent(class AGPQuestActionContext* QAContext, TSubclassOf<class AActor> ActorClass, class FName Tag, const class FString& Name_0, TSubclassOf<class UActorComponent> ComponentClass, EGPQuestActionScope Scope); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141001860
	static void QA_ObjectiveHint(class AGPQuestActionContext* QAContext, const class FText& InHintText, EGPQuestObjectiveHUDType InObjectiveHUDType); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141001A50
	static void QA_ObjectiveTips(class AGPQuestActionContext* QAContext, const class FText& InTipsText); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141001BB0
	static void QA_PlayObjectiveNotice(class AGPQuestActionContext* QAContext, const class FText& NoticeText, bool bNoticeAudio, float Duration, int32 Priority); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141001CD0
	static void QA_QuestStateUpdateTips(class AGPQuestActionContext* QAContext, const class FText& PopText, EGPQuestStageState State); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141001EA0
	static void QA_RemoveActorMarker(class AGPQuestActionContext* QAContext, TSubclassOf<class AGPQuestMarkerBase> MarkerClass, class AActor* TargetActor, EGPQuestActionScope Scope); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141002000
	static void QA_RemoveAllMarker(class AGPQuestActionContext* QAContext); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141002130
	static void QA_RemoveMarker(class AGPQuestActionContext* QAContext, TSubclassOf<class AGPQuestMarkerBase> MarkerClass, class FName QATag_TargetTag, EGPQuestActionScope Scope); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x1410021A0
	static void QA_RemoveSpecifiedMarker(class AGPQuestActionContext* QAContext, class AGPQuestMarkerBase* MarkerActor); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x1410022D0
	static void QA_SetObjectiveTitleAutoParams(class AGPQuestActionContext* QAContext, const class FText& InText, EGPQuestObjectiveHUDType InMissionHUDType, const TArray<class FString>& InArgs); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141002380
	static void QA_SetObjectiveTitleWithType(class AGPQuestActionContext* QAContext, const class FText& InText, EGPQuestObjectiveHUDType InMissionHUDType); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x1410025C0
	static void QA_SetOptionalObjectiveTitle(class AGPQuestActionContext* QAContext, const class FText& InTitle, EGPQuestObjectiveHUDType InMissionType); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141002720
	static void QA_SetOptionalObjectiveTitleWithHealthBar(class AGPQuestActionContext* QAContext, const class FText& InTitle, EGPQuestObjectiveHUDType InMissionType, TSubclassOf<class AActor> ActorClass, class FName QATag_TargetTag, EGPQuestActionScope Scope); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141002880
	static void QA_SetScreenLogVisible(class AGPQuestActionContext* QAContext, bool bVisible, float Duration); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141002A90
	static void QA_SetStageTitle(class AGPQuestActionContext* QAContext, const class FText& InStageTitle); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141002B90

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestActionLib_Basic")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestActionLib_Basic")
	}
	static class UGPQuestActionLib_Basic* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGPQuestActionLib_Basic>();
	}
};
DUMPER7_ASSERTS_UGPQuestActionLib_Basic;

// Class GPQuest.GPQuestAudioSubsystem
// 0x0078 (0x03E8 - 0x0370)
class AGPQuestAudioSubsystem : public AActor
{
public:
	class UDataTable*                             AudioDataTable2D;                                  // 0x0370(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UDataTable*                             AudioDataTable3D;                                  // 0x0378(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UDataTable*                             AudioDataTableCommon;                              // 0x0380(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FGPQuestPlayingAudioInfo>       PlayingAudiosInfo;                                 // 0x0388(0x0010)(Edit, Net, ZeroConstructor, EditConst, NativeAccessSpecifierPrivate)
	uint8                                         Pad_398[0x50];                                     // 0x0398(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void Play2DAudio(const class FName& AudioDataTableKey); // (Net, NetReliable, Native, Event, NetMulticast, Public) // @ 0x141000870
	void Play3DAudio(const class FName& AudioDataTableKey, const struct FVector& PlayingLocation); // (Net, NetReliable, Native, Event, NetMulticast, Public, HasDefaults) // @ 0x141000900
	void StopAudio(const class FName& AudioDataTableKey, int32 TransitionMS); // (Net, NetReliable, Native, Event, NetMulticast, Public) // @ 0x1410032E0

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestAudioSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestAudioSubsystem")
	}
	static class AGPQuestAudioSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGPQuestAudioSubsystem>();
	}
};
DUMPER7_ASSERTS_AGPQuestAudioSubsystem;

// Class GPQuest.GPQuestClientProxy
// 0x00F0 (0x0460 - 0x0370)
class AGPQuestClientProxy : public AActor
{
public:
	TMulticastInlineDelegate<void(ELootingStatus Status)> ServerLootingStatusBroadcast;              // 0x0370(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(bool bOpenBigMap)> ServerMapStatusBroadcast;                       // 0x0380(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              ServerHudViewsLoadedBroadcast;                     // 0x0390(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TArray<EGameHUDSate>                          AddedGameHudStates;                                // 0x03A0(0x0010)(BlueprintVisible, Net, ZeroConstructor, RepNotify, Protected, NativeAccessSpecifierProtected)
	TArray<EGameHUDSate>                          RemovedGameHudStates;                              // 0x03B0(0x0010)(BlueprintVisible, Net, ZeroConstructor, RepNotify, Protected, NativeAccessSpecifierProtected)
	struct FGPQuestObjectiveHUDInfo               ObjectiveHUDInfo;                                  // 0x03C0(0x0050)(BlueprintVisible, Net, RepNotify, Protected, NativeAccessSpecifierProtected)
	struct FGPQuestObjectiveHUDInfo               OptionalObjectiveHUDInfo;                          // 0x0410(0x0050)(BlueprintVisible, Net, RepNotify, Protected, NativeAccessSpecifierProtected)

public:
	void ClearOptionalObjective(); // (Final, Native, Public, BlueprintCallable) // @ 0x140FFF830
	void ClientAddGameHudState(EGameHUDSate State); // (Native, Public, BlueprintCallable) // @ 0x140FFF850
	void ClientHideActorInGame(class UClass* ActorClass, class FName actorTag, bool bHideInGame); // (Net, NetReliable, Native, Event, NetMulticast, Public, BlueprintCallable) // @ 0x140FFFA20
	void ClientHideHUDPanel(class FName PanelConfigName); // (Net, NetReliable, Native, Event, NetMulticast, Public, BlueprintCallable) // @ 0x140FFFB20
	void ClientHUDPanelsOperateGameHudState(const TArray<class FName>& PanelConfigNames, EGameHUDSate State, EVisibleGameHUDStateOperators Operator); // (Net, NetReliable, Native, Event, NetMulticast, Public, BlueprintCallable) // @ 0x140FFF8D0
	void ClientRemoveGameHudState(EGameHUDSate State); // (Native, Public, BlueprintCallable) // @ 0x140FFFBB0
	void ClientShowHUDPanel(class FName PanelConfigName); // (Net, NetReliable, Native, Event, NetMulticast, Public, BlueprintCallable) // @ 0x140FFFC30
	void ClientShowObjectiveHint(const class FString& HintText, EGPQuestObjectiveHUDType InObjectiveHUDType); // (Net, NetReliable, Native, Event, NetMulticast, Public, BlueprintCallable) // @ 0x140FFFCC0
	void ClientShowObjectiveTips(const class FString& TipsText); // (Net, NetReliable, Native, Event, NetMulticast, Public, BlueprintCallable) // @ 0x140FFFDD0
	void ClientsNotifyPlayObjectiveNotice(const struct FGPQuestObjectiveNoticeInfo& ObjectiveNoticeInfo); // (Net, NetReliable, Native, Event, NetMulticast, Public, BlueprintCallable) // @ 0x140FFFFA0
	void ClientUpdateQuestState(const class FText& PopText, EGPQuestStageState QuestState); // (Net, NetReliable, Native, Event, NetMulticast, Public, BlueprintCallable) // @ 0x140FFFEA0
	struct FGPQuestObjectiveHUDInfo GetObjectiveInfo(); // (Final, Native, Public, BlueprintCallable, BlueprintPure) // @ 0x141000190
	struct FGPQuestObjectiveHUDInfo GetOptionalObjectiveInfo(); // (Final, Native, Public, BlueprintCallable, BlueprintPure) // @ 0x141000210
	void NotifyHudViewLoaded(); // (Native, Public) // @ 0x141000510
	void NotifyServerLevelsLoaded(uint64 PlayerUin); // (Native, Public) // @ 0x141000530
	void NotifyServerMediaEnd(int64 PlayerUin, uint32 MediaNameCrc); // (Native, Public) // @ 0x1410005C0
	void OnCommonBannerShowed(const class FString& FunctionName, class UBaseUIView* View); // (Final, Native, Protected) // @ 0x141000690
	void OnRep_AddGameHudState(); // (Native, Protected) // @ 0x141000790
	void OnRep_ObjectiveInfo(); // (Native, Protected) // @ 0x141000810
	void OnRep_OptionalObjectiveHUDInfo(); // (Native, Protected) // @ 0x141000830
	void OnRep_RomoveGameHudState(); // (Native, Protected) // @ 0x141000850
	void SetActorDisableCollision(class UClass* ActorClass, class FName actorTag, bool bDisableCollision); // (Net, NetReliable, Native, Event, NetMulticast, Public, BlueprintCallable) // @ 0x141002F00
	void SetObjectiveHUDInfo(const struct FGPQuestObjectiveHUDInfo& InObjectiveInfo); // (Final, Native, Public, HasOutParams, BlueprintCallable) // @ 0x141003000
	void SetOptionalObjectiveInfo(const struct FGPQuestObjectiveHUDInfo& InObjectiveInfo); // (Final, Native, Public, HasOutParams, BlueprintCallable) // @ 0x141003130

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestClientProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestClientProxy")
	}
	static class AGPQuestClientProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGPQuestClientProxy>();
	}
};
DUMPER7_ASSERTS_AGPQuestClientProxy;

// Class GPQuest.GPQuestTextUtils
// 0x0000 (0x0028 - 0x0028)
class UGPQuestTextUtils final : public UBlueprintFunctionLibrary
{
public:
	static class FString GetDisplayString(const struct FGPQuestText& Text); // (Final, Native, Static, Public, HasOutParams, BlueprintCallable) // @ 0x141006CA0
	static class FText GetFinalText(const struct FGPQuestText& Text); // (Final, Native, Static, Public, HasOutParams, BlueprintCallable) // @ 0x141006DC0

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestTextUtils")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestTextUtils")
	}
	static class UGPQuestTextUtils* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGPQuestTextUtils>();
	}
};
DUMPER7_ASSERTS_UGPQuestTextUtils;

// Class GPQuest.GPQuestHUDSubsystem
// 0x00C0 (0x0430 - 0x0370)
class AGPQuestHUDSubsystem : public AActor
{
public:
	struct FGPQuestObjectiveHUDInfo               ObjectiveInfo;                                     // 0x0370(0x0050)(BlueprintVisible, NativeAccessSpecifierPublic)
	EGPQuestObjectiveState                        ObjectiveState;                                    // 0x03C0(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3C1[0x7];                                      // 0x03C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(const class FText& QuestText)> OnSetObjectiveTitleEvent;           // 0x03C8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(EGPQuestObjectiveState ObjState)> OnObjectiveStateChangedEvent;    // 0x03D8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const class FText& ObjectiveTitle, class AActor* TargetActor)> OnSetObjTitleWithHBarEvent; // 0x03E8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	class FText                                   StageTitle;                                        // 0x03F8(0x0018)(BlueprintVisible, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const class FText& QuestText)> OnSetStageTitleEvent;               // 0x0410(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FGPQuestObjectiveNoticeInfo& ObjectiveNoticeInfo)> OnPlayObjectiveNoticeEvent; // 0x0420(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestHUDSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestHUDSubsystem")
	}
	static class AGPQuestHUDSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGPQuestHUDSubsystem>();
	}
};
DUMPER7_ASSERTS_AGPQuestHUDSubsystem;

// Class GPQuest.GPQuestInteractorInterface
// 0x0000 (0x0000 - 0x0000)
class IGPQuestInteractorInterface final
{
public:
	void ActivateInteractor(); // (Event, Public, BlueprintCallable, BlueprintEvent) // @ 0x14B5B5E20
	void DeactivateInteractor(); // (Event, Public, BlueprintCallable, BlueprintEvent) // @ 0x14B5B5E20
	EGPQuestInteractorStatus GetInteractorStatus(); // (Event, Public, BlueprintCallable, BlueprintEvent) // @ 0x14B5B5E20
	void MakeInteractorFail(); // (Event, Public, BlueprintCallable, BlueprintEvent) // @ 0x14B5B5E20
	void MakeInteractorSuccessful(); // (Event, Public, BlueprintCallable, BlueprintEvent) // @ 0x14B5B5E20
	void OnStatusChanged_Broadcast(); // (Native, Event, Public, BlueprintCallable, BlueprintEvent) // @ 0x141007260

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestInteractorInterface")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestInteractorInterface")
	}
	static class IGPQuestInteractorInterface* GetDefaultObj()
	{
		return GetDefaultObjImpl<IGPQuestInteractorInterface>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IGPQuestInteractorInterface;

// Class GPQuest.GPQuestLevelResetComponent
// 0x0028 (0x0120 - 0x00F8)
class UGPQuestLevelResetComponent final : public UActorComponent
{
public:
	TMulticastInlineDelegate<void()>              OnLevelReset;                                      // 0x00F8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPrivate)
	TArray<struct FGPQuestReleventStageInfo>      RelevantStages;                                    // 0x0108(0x0010)(Edit, ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	bool                                          bListenResetEventOnce;                             // 0x0118(0x0001)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_119[0x7];                                      // 0x0119(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ListenLevelResetEventOnce(); // (Final, Native, Public, BlueprintCallable) // @ 0x1410070E0
	void OnResetStage(class AGPQuestStage* QStage); // (Final, Native, Protected) // @ 0x1410071E0
	void TestReset(); // (Final, Native, Protected) // @ 0x141007390

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestLevelResetComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestLevelResetComponent")
	}
	static class UGPQuestLevelResetComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGPQuestLevelResetComponent>();
	}
};
DUMPER7_ASSERTS_UGPQuestLevelResetComponent;

// Class GPQuest.GPQuestMarkerBase
// 0x00B0 (0x0420 - 0x0370)
class AGPQuestMarkerBase : public AActor
{
public:
	class UGPQuestRuleHelperComponent*            RuleHelper;                                        // 0x0370(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DistanceThreshold;                                 // 0x0378(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MarkerScale;                                       // 0x037C(0x0004)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGPQuestActionMarkerType                      markerType;                                        // 0x0380(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_381[0x3];                                      // 0x0381(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MarkerTimeLimit;                                   // 0x0384(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          AlwaysTop;                                         // 0x0388(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ShowInBigMap;                                      // 0x0389(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_38A[0xA];                                      // 0x038A(0x000A)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          MarkerActive;                                      // 0x0394(0x0001)(BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_395[0x3];                                      // 0x0395(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         MarkerActiveUpdate;                                // 0x0398(0x0004)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Client_AlwaysTop_Active;                           // 0x039C(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_39D[0x3];                                      // 0x039D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<uint64>                                ValidUins;                                         // 0x03A0(0x0010)(Net, ZeroConstructor, RepNotify, NativeAccessSpecifierPublic)
	class FString                                 DebugName;                                         // 0x03B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ShowMarkCircel;                                    // 0x03C0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3C1[0x3];                                      // 0x03C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                ShowMarkCircelOffset;                              // 0x03C4(0x000C)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                ShowMarkCircelScale;                               // 0x03D0(0x000C)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsUIOutMarkerArea;                                 // 0x03DC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsAimed;                                          // 0x03DD(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3DE[0x2];                                      // 0x03DE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MaxDistance;                                       // 0x03E0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              OriginMarkerPos;                                   // 0x03E4(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              EllipseAreaMarkerPos;                              // 0x03EC(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              OutScreenDir;                                      // 0x03F4(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3FC[0x8];                                      // 0x03FC(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                MarkerServerPos;                                   // 0x0404(0x000C)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UUserWidget*                            MarkerView;                                        // 0x0410(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_418[0x8];                                      // 0x0418(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ActivateMarker(); // (Final, Native, Public, BlueprintCallable) // @ 0x1410068A0
	void ActivateMarkerOnClient(); // (Net, NetReliable, Native, Event, NetMulticast, Public) // @ 0x1410000F0
	void DeactivateMarker(); // (Final, Native, Public, BlueprintCallable) // @ 0x141006B00
	void DeactivateMarkerOnClient(); // (Net, NetReliable, Native, Event, NetMulticast, Public) // @ 0x141006B20
	struct FVector2D GetUserWidgetLocation(const struct FVector2D& WidgetSize, const struct FVector2D& AnchorCenterOffset); // (Final, Native, Public, HasDefaults, BlueprintCallable) // @ 0x141006F60
	bool GetViewportAimMarkerActor(); // (Final, Native, Public, BlueprintCallable) // @ 0x141007020
	struct FVector2D GetViewportLocation(const struct FVector2D& AnchorCenterOffset); // (Final, Native, Public, HasDefaults, BlueprintCallable) // @ 0x141007050
	void OnActivateMarkerOnClient(); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void OnDeactivateMarkerOnClient(); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void OnGameHudStateChanged(); // (Final, Native, Public) // @ 0x141007100
	void OnMarkerViewCreatedOnClient(class UBaseUIView* View); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void OnRep_MarkerActive(); // (Final, Native, Public, BlueprintCallable) // @ 0x141007160
	void OnRep_MarkerScale(); // (Final, Native, Public) // @ 0x141007180
	void OnRep_MarkerServerPos(); // (Native, Public) // @ 0x140FFF810
	void OnRep_ShowInBigMap(); // (Native, Public) // @ 0x140FFF7F0
	void OnRep_ShowMarkCircel(); // (Final, Native, Public, BlueprintCallable) // @ 0x1410071A0
	void OnRep_ValidUins(); // (Final, Native, Public, BlueprintCallable) // @ 0x1410071C0
	void SetMarkerActive(bool Active); // (Final, Native, Public, BlueprintCallable) // @ 0x141007300
	void SetTargetWidgetScale(float Scale); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void ShowMarkCircelOnClient(); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void UpdateMarkerLoc(); // (Final, Native, Public) // @ 0x1410073B0

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestMarkerBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestMarkerBase")
	}
	static class AGPQuestMarkerBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGPQuestMarkerBase>();
	}
};
DUMPER7_ASSERTS_AGPQuestMarkerBase;

// Class GPQuest.GPQuestObjectiveAsyncReturnAction_Default
// 0x0020 (0x0060 - 0x0040)
class UGPQuestObjectiveAsyncReturnAction_Default final : public UGPQuestObjectiveAsyncReturnActionBase
{
public:
	TMulticastInlineDelegate<void()>              OnComplete;                                        // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnFailed;                                          // 0x0050(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UGPQuestObjectiveAsyncReturnAction_Default* BeginQuestObjective(class AGPQuestStage* QStage, int32 QObjective); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x1410068C0
	static class UGPQuestObjectiveAsyncReturnAction_Default* BeginQuestObjectiveNew(class AGPQuest* Quest, int32 QObjective); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141006980
	static class UGPQuestObjectiveAsyncReturnAction_Default* BeginQuestObjectiveNewWithTargetType(class AGPQuest* Quest, ESOLTargetType TargetType); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141006A40
	static void EndQuestObjective(class AGPQuestStage* QStage, EGPQuestObjectiveAsyncReturnBranch Branch); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141006B40
	static void EndQuestObjectiveNew(class AGPQuest* Quest, EGPQuestObjectiveAsyncReturnBranch Branch); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141006BF0

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestObjectiveAsyncReturnAction_Default")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestObjectiveAsyncReturnAction_Default")
	}
	static class UGPQuestObjectiveAsyncReturnAction_Default* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGPQuestObjectiveAsyncReturnAction_Default>();
	}
};
DUMPER7_ASSERTS_UGPQuestObjectiveAsyncReturnAction_Default;

// Class GPQuest.GPQuestRuleHelperComponent
// 0x0000 (0x00F8 - 0x00F8)
class UGPQuestRuleHelperComponent final : public UActorComponent
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestRuleHelperComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestRuleHelperComponent")
	}
	static class UGPQuestRuleHelperComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGPQuestRuleHelperComponent>();
	}
};
DUMPER7_ASSERTS_UGPQuestRuleHelperComponent;

// Class GPQuest.GPQuestSettings
// 0x0028 (0x0050 - 0x0028)
class UGPQuestSettings final : public UObject
{
public:
	TSubclassOf<class AGPQuest>                   QuestParentClass;                                  // 0x0028(0x0008)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class AGPQuestStage>              QuestStageParentClass;                             // 0x0030(0x0008)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class AGPQuestMarkerBase>         QuestDefaultMarkerClass;                           // 0x0038(0x0008)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class AGPQuestCountdownBase>      QuestDefaultCountdownClass;                        // 0x0040(0x0008)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableCleanupStageRelevantLevels;                 // 0x0048(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UGPQuestSettings* Get(); // (Final, Native, Static, Public) // @ 0x14100A2A0

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestSettings")
	}
	static class UGPQuestSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGPQuestSettings>();
	}
};
DUMPER7_ASSERTS_UGPQuestSettings;

// Class GPQuest.GPQuestStageAsyncReturnActionBase
// 0x0000 (0x0030 - 0x0030)
class UGPQuestStageAsyncReturnActionBase : public UBlueprintAsyncActionBase
{
public:
	void FireReturnAction(EGPQuestStageAsyncReturnBranch Branch); // (Native, Public, BlueprintCallable) // @ 0x141000110

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestStageAsyncReturnActionBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestStageAsyncReturnActionBase")
	}
	static class UGPQuestStageAsyncReturnActionBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGPQuestStageAsyncReturnActionBase>();
	}
};
DUMPER7_ASSERTS_UGPQuestStageAsyncReturnActionBase;

// Class GPQuest.GPQuestStage
// 0x0120 (0x0520 - 0x0400)
class AGPQuestStage final : public AGPQuestActionContext
{
public:
	class UGPQuestRuleHelperComponent*            RuleHelper;                                        // 0x0400(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UGPQuestStageAsyncReturnActionBase*     StageAsyncReturnAction;                            // 0x0408(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FName>                           ReturnActionPins;                                  // 0x0410(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	ENetRole                                      LocalNetRole;                                      // 0x0420(0x0001)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ENetRole                                      RemoteNetRole;                                     // 0x0421(0x0001)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_422[0x6];                                      // 0x0422(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AGPQuest*                               OwningQuest;                                       // 0x0428(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGPQuestStageData                      Data;                                              // 0x0430(0x0060)(Edit, BlueprintVisible, Net, NativeAccessSpecifierPublic)
	EGPQuestStageState                            StageState;                                        // 0x0490(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, EditConst, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGPQuestPlayReason                            PlayReason;                                        // 0x0491(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_492[0x6];                                      // 0x0492(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ULevelStreaming*                        QLevelStreaming;                                   // 0x0498(0x0008)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ULevel*                                 QLevel;                                            // 0x04A0(0x0008)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   QLevelFullName;                                    // 0x04A8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 QLevelBaseDir;                                     // 0x04B0(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 StageName;                                         // 0x04C0(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         StageId;                                           // 0x04D0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         OwningQuestId;                                     // 0x04D4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bPlaying;                                          // 0x04D8(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4D9[0x3];                                      // 0x04D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         StageObjectivesCount;                              // 0x04DC(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxResetStageDelay;                                // 0x04E0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bNeedResetStageWhenFailed;                         // 0x04E4(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4E5[0x3];                                      // 0x04E5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         StageTimeLimit;                                    // 0x04E8(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4EC[0x4];                                      // 0x04EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         RelevantLevels;                                    // 0x04F0(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<class FString>                         RelevantLevels_HD;                                 // 0x0500(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
	class FName                                   FadeUITextKeyName;                                 // 0x0510(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_518[0x8];                                      // 0x0518(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void BeginStage(EGPQuestPlayReason reason, TSubclassOf<class AGPQuestStage> LastStageClass); // (Native, Public) // @ 0x141009640
	void BreakStage(); // (Native, Public) // @ 0x140FFF810
	void CleanupLastStageRelevantLevelBroadcast(TSubclassOf<class AGPQuestStage> LastStageClass); // (Final, Net, NetReliable, Native, Event, NetMulticast, Private) // @ 0x1410097A0
	class AGPQuestClientProxy* ClientProxy(); // (Native, Public, BlueprintCallable, BlueprintPure) // @ 0x141009830
	void EndStage(); // (Native, Public) // @ 0x141009910
	void OnBeginStage(); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void OnEndStage(); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void OnPlayerReconnectToStage(class APlayerController* ReconnectPlayer); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void OnPreBeginStage(); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void OnRep_StageState(); // (Final, Native, Public) // @ 0x14100C330
	void OnResetStage(); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void OnResetStageClient(); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void OnResetStageComplete(); // (Final, Native, Private) // @ 0x14100C350
	void OnStageFailed(); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void ResetStageBroadcast(EGPQuestPlayReason reason); // (Final, Net, NetReliable, Native, Event, NetMulticast, Private) // @ 0x14100C840

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestStage")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestStage")
	}
	static class AGPQuestStage* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGPQuestStage>();
	}
};
DUMPER7_ASSERTS_AGPQuestStage;

// Class GPQuest.GPQuestStageAsyncReturnAction_Default
// 0x0060 (0x0090 - 0x0030)
class UGPQuestStageAsyncReturnAction_Default final : public UGPQuestStageAsyncReturnActionBase
{
public:
	TMulticastInlineDelegate<void()>              OnComplete;                                        // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnFailed;                                          // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_50[0x40];                                      // 0x0050(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static void EndStage(class AGPQuestStage* QStage, EGPQuestStageAsyncReturnBranch Branch); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141009930
	static class UGPQuestStageAsyncReturnAction_Default* PlayQuestStage(class AGPQuest* Quest, const class FText& StageTitle, const class FString& QStage, EGPQuestPlayReason reason); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x14100C370
	static class UGPQuestStageAsyncReturnAction_Default* PlayQuestStageAsync(class AGPQuest* Quest, const class FText& StageTitle, const class FString& StageName, EGPQuestPlayReason reason); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x14100C580
	static void ReplayQuestStage(class AGPQuest* Quest, EGPQuestPlayReason reason); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x14100C790

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestStageAsyncReturnAction_Default")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestStageAsyncReturnAction_Default")
	}
	static class UGPQuestStageAsyncReturnAction_Default* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGPQuestStageAsyncReturnAction_Default>();
	}
};
DUMPER7_ASSERTS_UGPQuestStageAsyncReturnAction_Default;

// Class GPQuest.GPQuestStageUtils
// 0x0000 (0x0028 - 0x0028)
class UGPQuestStageUtils final : public UBlueprintFunctionLibrary
{
public:
	static class ULevelStreaming* GetLevelStreamingByName(class AGPQuestStage* QStage, class FName QLevelFullName); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x14100A450
	static class FString GetObjectiveTitleKey(class AGPQuestStage* QStage, int32 objectiveId); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x14100A590
	static const struct FGPQuestStageData GetStageData(class AGPQuestStage* QStage); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x14100AB70
	static class ULevelStreaming* GetStageLevelStreaming(class AGPQuestStage* QStage); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x14100AE10
	static class FString GetStageSummaryKey(class AGPQuestStage* QStage); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x14100AFA0
	static class FString GetStageTitleKey(class AGPQuestStage* QStage); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x14100B070

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestStageUtils")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestStageUtils")
	}
	static class UGPQuestStageUtils* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGPQuestStageUtils>();
	}
};
DUMPER7_ASSERTS_UGPQuestStageUtils;

// Class GPQuest.GPQuestSystem
// 0x00C0 (0x00F0 - 0x0030)
class UGPQuestSystem : public UWorldSubsystem
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class AGPQuest* Quest)> OnPreBeginQuestEvent;                      // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(class AGPQuest* Quest)> OnPostEndQuestEvent;                       // 0x0048(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(class AGPQuestStage* QStage)> OnPreBeginStageEvent;                // 0x0058(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(class AGPQuestStage* QStage)> OnPostEndStageEvent;                 // 0x0068(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(class AGPQuestStage* QStage)> OnStageStateChangedEvent;            // 0x0078(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(class AGPQuestStage* QStage)> OnResetStageEvent;                   // 0x0088(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(int32 ObjectiveIdx)> OnPreBeginObjectiveEvent;                     // 0x0098(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(int32 ObjectiveIdx)> OnPostEndObjectiveEvent;                      // 0x00A8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(class AGPQuestStage* QStage)> OnReplayStageEvent;                  // 0x00B8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnNoReplayStageEvent;                              // 0x00C8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	class AGPQuest*                               CurrentQuest;                                      // 0x00D8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class AGPQuest*>                       PlayingQuests;                                     // 0x00E0(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)

public:
	class AGPQuest* GetQuest(int32 QuestID); // (Native, Public, BlueprintCallable) // @ 0x14100A940
	void GotoObjective(int32 QuestID, const class FString& StageName, int32 objectiveId); // (Final, Native, Public, BlueprintCallable) // @ 0x14100B330
	void GotoStage(int32 QuestID, const class FString& StageName); // (Final, Native, Public, BlueprintCallable) // @ 0x14100B470
	bool LoadQuest(class UObject* WorldContextObject, int32 QuestID, class AGPQuestVolume* GPQuestVolume); // (Native, Public, BlueprintCallable) // @ 0x14100B990
	void LoadQuestByQuestPathName(class UObject* WorldContextObject, const class FString& QuestPathName, int32 QuestID, class AGPQuestVolume* GPQuestVolume); // (Native, Public, BlueprintCallable) // @ 0x14100BAA0
	void LoadQuestInSpecifiedDir(class UObject* WorldContextObject, const class FString& QuestDir, int32 QuestID, class AGPQuestVolume* GPQuestVolume); // (Native, Public, BlueprintCallable) // @ 0x14100BC60
	class AGPQuest* LoadQuestInSpecifiedDirWithReturn(class UObject* WorldContextObject, const class FString& QuestDir, int32 QuestID, class AGPQuestVolume* GPQuestVolume); // (Native, Public, BlueprintCallable) // @ 0x14100BE20
	void QuitQuest(); // (Native, Public, BlueprintCallable) // @ 0x140EDBAC0
	void UnloadQuest(class UObject* WorldContextObject, int32 QuestID); // (Native, Public, BlueprintCallable) // @ 0x14100C940

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestSystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestSystem")
	}
	static class UGPQuestSystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGPQuestSystem>();
	}
};
DUMPER7_ASSERTS_UGPQuestSystem;

// Class GPQuest.GPQuestUtils
// 0x0000 (0x0028 - 0x0028)
class UGPQuestUtils final : public UBlueprintFunctionLibrary
{
public:
	static void EndQuest(class AGPQuest* Quest, EGPQuestEndReason EndReason); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141009860
	static void FindAllActor(class UObject* WorldContextObject, TSubclassOf<class AActor> ActorClass, class FName Tag, const class FString& Name_0, EGPQuestActionScope Scope, TArray<class AActor*>* OutActors); // (Final, Native, Static, Public, HasOutParams, BlueprintCallable) // @ 0x1410099E0
	static class AGPQuest* FindCurrentQuest(const class UObject* WorldContextObject); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141009C10
	static class AGPQuestStage* FindCurrentStage(const class UObject* WorldContextObject); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141009C90
	static class AActor* FindFirstActor(class UObject* WorldContextObject, TSubclassOf<class AActor> ActorClass, class FName Tag, const class FString& Name_0, EGPQuestActionScope Scope); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141009D10
	static class UActorComponent* FindFirstActorWithComponent(class UObject* WorldContextObject, TSubclassOf<class AActor> ActorClass, class FName Tag, const class FString& Name_0, TSubclassOf<class UActorComponent> ComponentClass, EGPQuestActionScope Scope); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x141009EC0
	static class AActor* FindFirstActorWithInterface(class UObject* WorldContextObject, TSubclassOf<class AActor> ActorClass, class FName Tag, const class FString& Name_0, TSubclassOf<class IInterface> InterfaceClass, EGPQuestActionScope Scope); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x14100A0B0
	static class AActor* GetActorByName(const class UObject* WorldContextObject, class FName Name_0); // (Final, Native, Static, Public, BlueprintCallable, BlueprintPure) // @ 0x14100A310
	static TArray<int32> GetAllQuests(); // (Final, Native, Static, Public, BlueprintCallable, BlueprintPure) // @ 0x14100A3D0
	static class APlayerController* GetLocalPlayerController(class UObject* WorldContextObject); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x14100A510
	static int32 GetObjectivesNameInStage(TSubclassOf<class AGPQuestStage> StageClass, TArray<class FString>* OutNames); // (Final, Native, Static, Public, HasOutParams, BlueprintCallable, BlueprintPure) // @ 0x14100A6A0
	static int32 GetObjectivesNumInStage(const class UObject* WorldContextObject, int32 QuestID, const class FString& StageName); // (Final, Native, Static, Public, BlueprintCallable, BlueprintPure) // @ 0x14100A800
	static TArray<int32> GetQuestsInWorld(const class UObject* WorldContextObject); // (Final, Native, Static, Public, BlueprintCallable, BlueprintPure) // @ 0x14100AAA0
	static int32 GetStageId(const class FString& StageName); // (Final, Native, Static, Public, BlueprintCallable, BlueprintPure) // @ 0x14100ACF0
	static class FString GetStageName(int32 QuestID, int32 StageId); // (Final, Native, Static, Public, BlueprintCallable, BlueprintPure) // @ 0x14100AE90
	static TArray<class FString> GetStagesInQuest(const class UObject* WorldContextObject, int32 QuestID); // (Final, Native, Static, Public, BlueprintCallable, BlueprintPure) // @ 0x14100B140
	static bool HasLocalPlayer(class UObject* WorldContextObject); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x14100B570
	static bool IsClient(const class UObject* WorldContextObject, bool bIncludeStandalone); // (Final, Native, Static, Public, BlueprintCallable, BlueprintPure) // @ 0x14100B5F0
	static bool IsEditor(const class UObject* WorldContextObject); // (Final, Native, Static, Public, BlueprintCallable, BlueprintPure) // @ 0x14100B6B0
	static bool IsPC(const class UObject* WorldContextObject); // (Final, Native, Static, Public, BlueprintCallable, BlueprintPure) // @ 0x14100B730
	static bool IsServer(const class UObject* WorldContextObject, bool bIncludeStandalone); // (Final, Native, Static, Public, BlueprintCallable, BlueprintPure) // @ 0x14100B850
	static bool IsStandalone(const class UObject* WorldContextObject); // (Final, Native, Static, Public, BlueprintCallable, BlueprintPure) // @ 0x14100B910
	static class AGPQuest* ToQuest(class AGPQuestActionContext* QAContext); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x14100C8C0

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestUtils")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestUtils")
	}
	static class UGPQuestUtils* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGPQuestUtils>();
	}
};
DUMPER7_ASSERTS_UGPQuestUtils;

// Class GPQuest.GPQuestVolume
// 0x00B0 (0x0420 - 0x0370)
class AGPQuestVolume : public AActor
{
public:
	bool                                          bEnableRangeRadius;                                // 0x0370(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_371[0x7];                                      // 0x0371(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FQuestFullID                           QuestFullID;                                       // 0x0378(0x0010)(Edit, BlueprintVisible, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	EQuestVolumeShape                             QuestVolumeShape;                                  // 0x0388(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_389[0x3];                                      // 0x0389(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CylinderRadius;                                    // 0x038C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         CylinderHalfHeight;                                // 0x0390(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_394[0x4];                                      // 0x0394(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CylinderShapeMeshPath;                             // 0x0398(0x0010)(Edit, BlueprintVisible, ZeroConstructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         CylinderMeshOrginalRadius;                         // 0x03A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         CylinderMeshOrginalHalfHeight;                     // 0x03AC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UPrimitiveComponent*                    QuestVolumeTrigger;                                // 0x03B0(0x0008)(Edit, ExportObject, ZeroConstructor, EditConst, InstancedReference, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         SOLQuestCDOId;                                     // 0x03B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_3BC[0x4];                                      // 0x03BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         InQuestVolumeActors;                               // 0x03C0(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	class AGPQuest*                               GPQuest;                                           // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3D8[0x4];                                      // 0x03D8(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ContractTeamID;                                    // 0x03DC(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ContractCampID;                                    // 0x03E0(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         OriginCampID;                                      // 0x03E4(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FText                                   ObjectionDes;                                      // 0x03E8(0x0018)(BlueprintVisible, NativeAccessSpecifierPublic)
	class FText                                   BriefObjectionDes;                                 // 0x0400(0x0018)(BlueprintVisible, NativeAccessSpecifierPublic)
	bool                                          IsTeamShared;                                      // 0x0418(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_419[0x7];                                      // 0x0419(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void BP_InitQuestData(const class AGPQuest* InGPQuest); // (Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void ChangeContractCamp(int32 CampId); // (Native, Public) // @ 0x141009710
	struct FQuestFullID GetQuestFullID(); // (Final, Native, Public, BlueprintCallable) // @ 0x14100A9E0
	class FString GetQuestIDString(); // (Final, Native, Public, BlueprintCallable) // @ 0x14100AA10
	bool IsRelevancyForConnection(class AActor* ViewTarget); // (Native, Public) // @ 0x14100B7B0
	void OnQuestAreaTriggerBeginOverlapped(class UPrimitiveComponent* OverlappedComp, class AActor* Other, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult); // (Native, Protected, HasOutParams) // @ 0x14100BFF0
	void OnQuestAreaTriggerEndOverlapped(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex); // (Native, Protected) // @ 0x14100C1F0
	void ResetContractCamp(); // (Native, Public) // @ 0x140FFF7F0
	void UpdateCylinderSize(); // (Final, Native, Protected, BlueprintCallable) // @ 0x14100CA10
	void UpdateQuestVolumeTrigger(); // (Final, Native, Protected, BlueprintCallable) // @ 0x14100CA30

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPQuestVolume")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPQuestVolume")
	}
	static class AGPQuestVolume* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGPQuestVolume>();
	}
};
DUMPER7_ASSERTS_AGPQuestVolume;

// Class GPQuest.GPTQuestContext
// 0x0048 (0x0070 - 0x0028)
class UGPTQuestContext final : public UObject
{
public:
	uint8                                         Pad_28[0x48];                                      // 0x0028(0x0048)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPTQuestContext")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPTQuestContext")
	}
	static class UGPTQuestContext* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGPTQuestContext>();
	}
};
DUMPER7_ASSERTS_UGPTQuestContext;

// Class GPQuest.GPTRPCQuestComponent
// 0x0000 (0x00F8 - 0x00F8)
class UGPTRPCQuestComponent final : public UActorComponent
{
public:
	static void BeginQuest(class AGPQuest* Quest); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x14100D240
	static void GotoObjective(class AGPQuestStage* Stage, int32 objectiveId); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x14100D2B0
	static void GotoStage(class AGPQuest* Quest, const class FString& StageName); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x14100D360
	static void ReplayStage(class AGPQuest* Quest); // (Final, Native, Static, Public, BlueprintCallable) // @ 0x14100D450

	void ServerBeginQuest(class AGPQuest* Quest); // (Net, NetReliable, Native, Event, Protected, NetServer) // @ 0x14100D4C0
	void ServerGotoObjective(class AGPQuestStage* Stage, int32 objectiveId); // (Net, NetReliable, Native, Event, Protected, NetServer) // @ 0x14100D550
	void ServerGotoStage(class AGPQuest* Quest, const class FString& StageName); // (Net, NetReliable, Native, Event, Protected, NetServer) // @ 0x14100D620
	void ServerReplayStage(class AGPQuest* Quest); // (Net, NetReliable, Native, Event, Protected, NetServer) // @ 0x14100D730

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPTRPCQuestComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPTRPCQuestComponent")
	}
	static class UGPTRPCQuestComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGPTRPCQuestComponent>();
	}
};
DUMPER7_ASSERTS_UGPTRPCQuestComponent;

// Class GPQuest.GPTQuestNative
// 0x0008 (0x0058 - 0x0050)
class UGPTQuestNative final : public UGPToolBase
{
public:
	class UGPTQuestContext*                       Context;                                           // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GPTQuestNative")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GPTQuestNative")
	}
	static class UGPTQuestNative* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGPTQuestNative>();
	}
};
DUMPER7_ASSERTS_UGPTQuestNative;

}

