#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GPWeaponDefineForPlugin

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// Enum GPWeaponDefineForPlugin.EStateDepFrameCheckMode
// NumValues: 0x0004
enum class EStateDepFrameCheckMode : uint8
{
	NONE                                     = 0,
	NORMAL_MODE                              = 1,
	STRICT_MODE                              = 2,
	EStateDepFrameCheckMode_MAX              = 3,
};

// Enum GPWeaponDefineForPlugin.ESwitchWeaponContext
// NumValues: 0x0028
enum class ESwitchWeaponContext : uint8
{
	Default                                  = 0,
	Client                                   = 1,
	Init                                     = 2,
	Input                                    = 3,
	Interact                                 = 4,
	Preview                                  = 5,
	AIController                             = 6,
	AILab                                    = 7,
	AITask                                   = 8,
	SafeHouse                                = 9,
	DSLogic                                  = 10,
	InventoryManager                         = 11,
	BattleFieldCharacter                     = 12,
	Ability                                  = 13,
	AIDifficulty                             = 14,
	Skill                                    = 15,
	Looting                                  = 16,
	FuncPVE                                  = 17,
	RemoveWeapon                             = 18,
	Character                                = 19,
	MachineGun                               = 20,
	Vehicle                                  = 21,
	SkillEnd                                 = 22,
	Reborn                                   = 23,
	WeaponBlueprint                          = 24,
	WeaponBase                               = 25,
	InitDefWeapon                            = 26,
	CharacterBase                            = 27,
	ImpendingDeathAction                     = 28,
	SOLEscapedStateAction                    = 29,
	SwitchEmptyHandComponent                 = 30,
	OnHelicopterAction                       = 31,
	GM                                       = 32,
	CancelSwitchWeapon                       = 33,
	FastFire                                 = 34,
	JailBreak                                = 35,
	SwimmingSprintBegin                      = 36,
	SwimmingSprintEnd                        = 37,
	ReconnectPutBackLeftWeapon               = 38,
	ESwitchWeaponContext_MAX                 = 39,
};

// Enum GPWeaponDefineForPlugin.EWeaponAutoReloadOption
// NumValues: 0x0003
enum class EWeaponAutoReloadOption : uint8
{
	OncePerState                             = 0,
	Always                                   = 1,
	EWeaponAutoReloadOption_MAX              = 2,
};

// Enum GPWeaponDefineForPlugin.EHeadDetailType
// NumValues: 0x0009
enum class EHeadDetailType : uint8
{
	None                                     = 0,
	Head                                     = 1,
	FrontHead                                = 2,
	FrontHeadDown                            = 3,
	LeftHead                                 = 4,
	RightHead                                = 5,
	BackHead                                 = 6,
	TopHead                                  = 7,
	EHeadDetailType_MAX                      = 8,
};

// Enum GPWeaponDefineForPlugin.EWeaponCancelCurrentStateReason
// NumValues: 0x001B
enum class EWeaponCancelCurrentStateReason : uint8
{
	GM                                       = 0,
	Knockback                                = 1,
	CancelWeaponReload                       = 2,
	InteractivePutWeapon                     = 3,
	TwoHandedGestureAction                   = 4,
	VaultAndClimb                            = 5,
	ApplySprayAction                         = 6,
	AssassinateGlobalAction                  = 7,
	OneHandedGestureAction                   = 8,
	RescueOperateAction                      = 9,
	SwitchClickSkillWeapon                   = 10,
	EnterSkillState                          = 11,
	WeaponBlueprintLibrary                   = 12,
	BowCancelCharging                        = 13,
	AbilityStopFire                          = 14,
	CancelPreFire                            = 15,
	VehicleStateChange                       = 16,
	Parachute                                = 17,
	Emote                                    = 18,
	Helmet                                   = 19,
	SlidingTackle                            = 20,
	SkillCharacterStateConflict              = 21,
	EMPBuff                                  = 22,
	SwimmingSprint                           = 23,
	NetBuff                                  = 24,
	Zipline                                  = 25,
	EWeaponCancelCurrentStateReason_MAX      = 26,
};

// Enum GPWeaponDefineForPlugin.EGPWeaponTickFrequency
// NumValues: 0x0006
enum class EGPWeaponTickFrequency : uint8
{
	Normal                                   = 0,
	High                                     = 1,
	Middle                                   = 2,
	Low                                      = 3,
	NotTick                                  = 4,
	EGPWeaponTickFrequency_MAX               = 5,
};

// Enum GPWeaponDefineForPlugin.EGPWeaponFireSocketMode
// NumValues: 0x0005
enum class EGPWeaponFireSocketMode : uint8
{
	Single                                   = 0,
	Loop                                     = 1,
	Random                                   = 2,
	MeshOrder                                = 3,
	EGPWeaponFireSocketMode_MAX              = 4,
};

// Enum GPWeaponDefineForPlugin.EWeaponMeshHideReason
// NumValues: 0x0006
enum class EWeaponMeshHideReason : uint8
{
	FuncAppearance                           = 0,
	FireThrowableWeapon                      = 1,
	FPPInteraction                           = 2,
	ThrowableWeaponAnimNotify                = 3,
	SocketNotExist                           = 4,
	EWeaponMeshHideReason_MAX                = 5,
};

// Enum GPWeaponDefineForPlugin.EWeaponAddAmmoType
// NumValues: 0x0004
enum class EWeaponAddAmmoType : uint8
{
	AddWithNum                               = 0,
	AddWithPercent                           = 1,
	AddToFull                                = 2,
	EWeaponAddAmmoType_MAX                   = 3,
};

// Enum GPWeaponDefineForPlugin.EWeaponConsumeAmmoType
// NumValues: 0x0004
enum class EWeaponConsumeAmmoType : uint8
{
	Normal                                   = 0,
	FireFreeAmmo                             = 1,
	RloadFreeAmmo                            = 2,
	EWeaponConsumeAmmoType_MAX               = 3,
};

// Enum GPWeaponDefineForPlugin.EInteractivePutWeaponType
// NumValues: 0x0004
enum class EInteractivePutWeaponType : uint8
{
	FastUnEquip                              = 1,
	NomalUnEquip                             = 2,
	QuietUnEquip                             = 3,
	EInteractivePutWeaponType_MAX            = 4,
};

// Enum GPWeaponDefineForPlugin.EInteractiveGetWeaponType
// NumValues: 0x0004
enum class EInteractiveGetWeaponType : uint8
{
	FastEquip                                = 1,
	NomalEquip                               = 2,
	QuietEquip                               = 3,
	EInteractiveGetWeaponType_MAX            = 4,
};

// Enum GPWeaponDefineForPlugin.EWeaponSwitchType
// NumValues: 0x000A
enum class EWeaponSwitchType : uint8
{
	Default                                  = 0,
	Quiet                                    = 1,
	Instant                                  = 2,
	GetWeaponQuiet                           = 3,
	PutWeaponQuiet                           = 4,
	GetWeaponFast                            = 5,
	PutWeaponFast                            = 6,
	GetAndPutWeaponFast                      = 7,
	PutQuietAndGetWeaponFast                 = 8,
	EWeaponSwitchType_MAX                    = 9,
};

// Enum GPWeaponDefineForPlugin.EGPThrowableWeaponTypeForADS
// NumValues: 0x0004
enum class EGPThrowableWeaponTypeForADS : uint8
{
	Damage                                   = 0,
	Special                                  = 1,
	Placement                                = 2,
	Max                                      = 3,
};

// Enum GPWeaponDefineForPlugin.EGPWeaponChangeClipMode
// NumValues: 0x0004
enum class EGPWeaponChangeClipMode : uint8
{
	Replace                                  = 0,
	OneByOne                                 = 1,
	TooHotToReload                           = 2,
	EGPWeaponChangeClipMode_MAX              = 3,
};

// Enum GPWeaponDefineForPlugin.EGPWeaponFiringRateMode
// NumValues: 0x0003
enum class EGPWeaponFiringRateMode : uint8
{
	Auto                                     = 0,
	Burst                                    = 1,
	Max                                      = 2,
};

// Enum GPWeaponDefineForPlugin.EGPWeaponFiringMode
// NumValues: 0x0007
enum class EGPWeaponFiringMode : uint8
{
	Auto                                     = 0,
	Single                                   = 1,
	AutoBurst                                = 2,
	Burst                                    = 3,
	ThrowHigh                                = 4,
	ThrowLow                                 = 5,
	Max                                      = 6,
};

// Enum GPWeaponDefineForPlugin.EProjectileMedium
// NumValues: 0x0004
enum class EProjectileMedium : uint8
{
	None                                     = 0,
	Air                                      = 1,
	Water                                    = 2,
	EProjectileMedium_MAX                    = 3,
};

// Enum GPWeaponDefineForPlugin.EGPWeaponStateEvent
// NumValues: 0x001F
enum class EGPWeaponStateEvent : uint8
{
	EStateEvent_None                         = 0,
	EStateEvent_Activate                     = 1,
	EStateEvent_ActivateNotEquip             = 2,
	EStateEvent_BeginFire                    = 3,
	EStateEvent_BeginZoomAndFire             = 4,
	EStateEvent_EndFire                      = 5,
	EStateEvent_BeginAltFire                 = 6,
	EStateEvent_EndAltFire                   = 7,
	EStateEvent_BeginChangeClip              = 8,
	EStateEvent_CancelChangeClip             = 9,
	EStateEvent_CancelChangeClipSingle       = 10,
	EStateEvent_Deactivate                   = 11,
	EStateEvent_PutBackWeapon                = 12,
	EStateEvent_PutBackWeaponNotUnEquip      = 13,
	EStateEvent_BeginZooming                 = 14,
	EStateEvent_EndZooming                   = 15,
	EStateEvent_Pickup                       = 16,
	EStateEvent_StopShootAiming              = 17,
	EStateEvent_BeginSwitchFireMode          = 18,
	EStateEvent_NotifyBreak                  = 19,
	EStateEvent_CancelFire                   = 20,
	EStateEvent_CancelCurrentState           = 21,
	EStateEvent_BeginInteraction             = 22,
	EStateEvent_EndInteraction               = 23,
	EStateEvent_BeginSwitchPot               = 24,
	EStateEvent_BeginLeftHold                = 25,
	EStateEvent_EndLeftHold                  = 26,
	EStateEvent_BeginSawAttack               = 27,
	EStateEvent_EndSawAttack                 = 28,
	EStateEvent_CancelCharging               = 29,
	EStateEvent_Max                          = 30,
};

// Enum GPWeaponDefineForPlugin.EGPWeaponStateType
// NumValues: 0x0017
enum class EGPWeaponStateType : uint8
{
	EWeapState_None                          = 0,
	EWeapState_Active                        = 1,
	EWeapState_Inactive                      = 2,
	EWeapState_Equipping                     = 3,
	EWeapState_Unequipping                   = 4,
	EWeapState_PreFire                       = 5,
	EWeapState_KeepPreFire                   = 6,
	EWeapState_Firing                        = 7,
	EWeapState_PostFire                      = 8,
	EWeapState_ChangingClip                  = 9,
	EWeapState_Chamber                       = 10,
	EWeapState_Interaction                   = 11,
	EWeapState_Zoom                          = 12,
	EWeapState_AltFiring                     = 13,
	EWeapState_ZoomTransition                = 14,
	EWeapState_SwitchFireMode                = 15,
	EWeapState_BeginingInteraction           = 16,
	EWeapState_CancelPreFire                 = 17,
	EWeapState_EndingInteraction             = 18,
	EWeapState_SwitchPot                     = 19,
	EWeapState_LeftHold                      = 20,
	EWeapState_SawAttackState                = 21,
	EWeapState_MAX                           = 22,
};

// Enum GPWeaponDefineForPlugin.EGPWeaponAttachBackConflict
// NumValues: 0x0003
enum class EGPWeaponAttachBackConflict : uint8
{
	None                                     = 0,
	LunaDoubleBow                            = 1,
	EGPWeaponAttachBackConflict_MAX          = 2,
};

// Enum GPWeaponDefineForPlugin.EGPWeaponAttachBackSocket
// NumValues: 0x0005
enum class EGPWeaponAttachBackSocket : uint8
{
	None                                     = 0,
	Left                                     = 1,
	Right                                    = 2,
	Middle                                   = 3,
	EGPWeaponAttachBackSocket_MAX            = 4,
};

// Enum GPWeaponDefineForPlugin.EGPWeaponAppearanceAttachType
// NumValues: 0x0008
enum class EGPWeaponAppearanceAttachType : uint8
{
	None                                     = 0,
	Primary                                  = 1,
	Assistant                                = 2,
	Grenade                                  = 3,
	MeleeWeapon                              = 4,
	Pistol                                   = 5,
	SecondaryWeapon                          = 6,
	EGPWeaponAppearanceAttachType_MAX        = 7,
};

// Enum GPWeaponDefineForPlugin.EGPWeaponAppearanceMeshType
// NumValues: 0x0003
enum class EGPWeaponAppearanceMeshType : uint8
{
	ThirdPersonMesh                          = 0,
	FirstPersonMesh                          = 1,
	EGPWeaponAppearanceMeshType_MAX          = 2,
};

// Enum GPWeaponDefineForPlugin.EGPComponentSpawnCondition
// NumValues: 0x0008
enum class EGPComponentSpawnCondition : uint8
{
	ECompInitCond_AlwaysSpawn                = 0,
	ECompInitCond_Logic                      = 1,
	ECompInitCond_Client                     = 2,
	ECompInitCond_Server                     = 3,
	ECompInitCond_NotOwned_Tpp_Client        = 4,
	ECompInitCond_Fpp_Client                 = 5,
	ECompInitCond_LocalFocus_Client          = 6,
	ECompInitCond_MAX                        = 7,
};

// Enum GPWeaponDefineForPlugin.EGPWeaponInnerEvent
// NumValues: 0x009C
enum class EGPWeaponInnerEvent : uint8
{
	EInnerEvent_None                         = 0,
	EStateEvent_SwitchToIdle                 = 1,
	EStateEvent_BeginEquip                   = 2,
	EStateEvent_EndEquip                     = 3,
	EStateEvent_PreFire                      = 4,
	EStateEvent_BeginKeepPreFire             = 5,
	EStateEvent_EndKeepPreFire               = 6,
	EStateEvent_BeginLeftHold                = 7,
	EStateEvent_EndLeftHold                  = 8,
	EStateEvent_TimeoutAutoFire              = 9,
	EStateEvent_CancelFire                   = 10,
	EStateEvent_BeginFire                    = 11,
	EStateEvent_AutoBurstGroupEnd            = 12,
	EStateEvent_NoDelayEndFire               = 13,
	EStateEvent_EndFire                      = 14,
	EStateEvent_FireModeProxyStateDirty      = 15,
	EStateEvent_MeleeRealFire                = 16,
	EStateEvent_SawAttackFire                = 17,
	EStateEvent_PlugAfterFire                = 18,
	EStateEvent_AfterFire                    = 19,
	EStateEvent_ZoomAfterPlug                = 20,
	EStateEvent_BeginJumpFire                = 21,
	EStateEvent_BeginZoom                    = 22,
	EStateEvent_BeginZoomAction              = 23,
	EStateEvent_EndZoom                      = 24,
	EStateEvent_BeginChangeClip              = 25,
	EStateEvent_CancelChangeClip             = 26,
	EStateEvent_BeginChangeClipLogic         = 27,
	EStateEvent_BeginChangeClip_Single       = 28,
	EStateEvent_BeginChangeClip_Single_End   = 29,
	EStateEvent_BeginChangeClip_FirstPartalSingle = 30,
	EStateEvent_BeginChangeClip_ContinuePartalSingle = 31,
	EStateEvent_BeginChangeClip_EmptyReload  = 32,
	EStateEvent_BeginChangeClip_Normal       = 33,
	EStateEvent_EndChangeClip                = 34,
	EStateEvent_SwitchToInactive             = 35,
	EStateEvent_BeginInteraction             = 36,
	EStateEvent_EndInteraction               = 37,
	EStateEvent_SwitchToInteraction          = 38,
	EStateEvent_BeginSwitchPot               = 39,
	EStateEvent_DoSwitchPot                  = 40,
	EStateEvent_EmptyClip                    = 41,
	EStateEvent_DryFire                      = 42,
	EStateEvent_StandToCrouch                = 43,
	EStateEvent_StandToProne                 = 44,
	EStateEvent_CrouchToStand                = 45,
	EStateEvent_CrouchToProne                = 46,
	EStateEvent_ProneToStand                 = 47,
	EStateEvent_ProneToCrouch                = 48,
	EStateEvent_InstantHit                   = 49,
	EStateEvent_SprayHit                     = 50,
	EStateEvent_BulletEffect                 = 51,
	EStateEvent_PenetratingMedium            = 52,
	EStateEvent_BeginSwitchFireMode          = 53,
	EStateEvent_EndSwitchFireMode            = 54,
	EStateEvent_BeginSawAttack               = 55,
	EStateEvent_EndSawAttack                 = 56,
	EStateEvent_ConfigBecomeEffective        = 57,
	EStateEvent_DoFire                       = 58,
	EStateEvent_ReEquip                      = 59,
	EStateEvent_StateCacheBeginFire          = 60,
	EStateEvent_StateCacheEndFire            = 61,
	EStateEvent_PutBackWeaponNotUnEquip      = 62,
	EStateEvent_PutBackWeapon                = 63,
	EStateEvent_Max                          = 64,
	EStateEvent_NotifyBreak                  = 65,
	EStateEvent_BreakEquip                   = 66,
	EInnerEvent_DoBeginZoom                  = 67,
	EInnerEvent_DoEndZoom                    = 68,
	EInnerEvent_OverHeat                     = 69,
	EInnerEvent_CoolDown                     = 70,
	EInnerEvent_CompoleteCoolDown            = 71,
	EInnerEvent_CompleteLocking              = 72,
	EInnerEvent_ModifyFireModeIndex          = 73,
	EInnerEvent_ModifyFiringModeType         = 74,
	EInnerEvent_NextFiringModeType           = 75,
	EInnerEvent_FiringModeTypeChanged        = 76,
	EInnerEvent_ModifyWeaponParts            = 77,
	EInnerEvent_ModifyWeaponPartsReady       = 78,
	EInnerEvent_InitModularWeaponParts       = 79,
	EInnerEvent_ShowFullAmmoMag              = 80,
	EInnerEvent_WeaponPartsDynamicAttrModifed = 81,
	EInnerEvent_WeaponAmmoDynamicAttrModifed = 82,
	EInnerEvent_WriteWeaponPartsDynamicAttr  = 83,
	EInnerEvent_RotationBegin                = 84,
	EInnerEvent_RotationEnd                  = 85,
	EInnerEvent_EquipPerk                    = 86,
	EInnerEvent_UnEquipPerk                  = 87,
	EInnerEvent_ClearState                   = 88,
	EInnerEvent_OwnerReplicated              = 89,
	EInnerEvent_OnInitAbilityActorInfo       = 90,
	EInnerEvent_3PExtraDataReplicated        = 91,
	EInnerEvent_StateChanged                 = 92,
	EInnerEvent_BeginInspect                 = 93,
	EInnerEvent_EndInspect                   = 94,
	EInnerEvent_MakeDamage                   = 95,
	EInnerEvent_BulletHit                    = 96,
	EInnerEvent_BeginChamber                 = 97,
	EInnerEvent_ChamberMax                   = 98,
	EInnerEvent_CancelChamber                = 99,
	EInnerEvent_EndChamber                   = 100,
	EInnerEvent_AnimShellDrop                = 101,
	EInnerEvent_Charging                     = 102,
	EInnerEvent_CancelCharge                 = 103,
	EInnerEvent_AnimEndFire                  = 104,
	EInnerEvent_ScopeParamOverrideChanged    = 105,
	EInnerEvent_ResetWeaponState             = 106,
	EInnerEvent_OBPendingBeginFire           = 107,
	EInnerEvent_Max                          = 108,
	EStateEvent_Extend01                     = 109,
	EInnerEvent_WeaponMeshAttached           = 110,
	EInnerEvent_BipodUp                      = 111,
	EInnerEvent_BipodDown                    = 112,
	EInnerEvent_PowerFlashOn                 = 113,
	EInnerEvent_TacticalEquipUOn             = 114,
	EInnerEvent_TacticalEquipUOff            = 115,
	EInnerEvent_TacticalEquipU1On            = 116,
	EInnerEvent_TacticalEquipU1Off           = 117,
	EInnerEvent_TacticalEquipU2On            = 118,
	EInnerEvent_TacticalEquipU2Off           = 119,
	EInnerEvent_TacticalEquipROn             = 120,
	EInnerEvent_TacticalEquipROff            = 121,
	EInnerEvent_TacticalEquipR1On            = 122,
	EInnerEvent_TacticalEquipR1Off           = 123,
	EInnerEvent_TacticalEquipR2On            = 124,
	EInnerEvent_TacticalEquipR2Off           = 125,
	EInnerEvent_TacticalEquipDOn             = 126,
	EInnerEvent_TacticalEquipDOff            = 127,
	EInnerEvent_TacticalEquipD1On            = 128,
	EInnerEvent_TacticalEquipD1Off           = 129,
	EInnerEvent_TacticalEquipD2On            = 130,
	EInnerEvent_TacticalEquipD2Off           = 131,
	EInnerEvent_TacticalEquipLOn             = 132,
	EInnerEvent_TacticalEquipLOff            = 133,
	EInnerEvent_TacticalEquipL1On            = 134,
	EInnerEvent_TacticalEquipL1Off           = 135,
	EInnerEvent_TacticalEquipL2On            = 136,
	EInnerEvent_TacticalEquipL2Off           = 137,
	EInnerEvent_SwitchRangeScope             = 138,
	EInnerEvent_BeginSideAiming              = 139,
	EInnerEvent_EndSideAiming                = 140,
	EInnerEvent_SwitchLaser                  = 141,
	EInnerEvent_ToggleRangeFinder            = 142,
	EInnerEvent_CharacterOwnerChanged        = 143,
	ENZAdapterEvent_Extend01                 = 144,
	EInnerEvent_AutoAddAmmoComplete          = 145,
	EStateEvent_LauncherBeginFire            = 146,
	EInnerEvent_ChainHook_HitTarget          = 147,
	EInnerEvent_ChainHook_PullBackLoop       = 148,
	EInnerEvent_ChainHook_PullBackSuccess    = 149,
	EInnerEvent_ChainHook_PullBackBreak      = 150,
	EInnerEvent_ChainHook_PullBackNoneLoop   = 151,
	EInnerEvent_ChainHook_PullBackNoneSuccess = 152,
	EInnerEvent_ToggleSkillWeaponExtraFunc   = 153,
	EInnerEvent_InstantHitFor1P              = 154,
	EGPWeaponInnerEvent_MAX                  = 155,
};

// Enum GPWeaponDefineForPlugin.EGPWeaponMode
// NumValues: 0x0006
enum class EGPWeaponMode : uint8
{
	EWeapMode_None                           = 0,
	EWeapMode_OwnerFirstPerson               = 1,
	EWeapMode_OwnerThirdPerson               = 2,
	EWeapMode_ObserverFirstPerson            = 3,
	EWeapMode_ThirdPerson                    = 4,
	EWeapMode_MAX                            = 5,
};

// Enum GPWeaponDefineForPlugin.EFireCrackerType
// NumValues: 0x0005
enum class EFireCrackerType : uint8
{
	HoldPerform                              = 0,
	SettleStill                              = 1,
	SettleLaunch                             = 2,
	SettleLaunch_Real                        = 3,
	EFireCrackerType_MAX                     = 4,
};

// Enum GPWeaponDefineForPlugin.EPenetrateAttenuationType
// NumValues: 0x0004
enum class EPenetrateAttenuationType : uint8
{
	Never                                    = 0,
	Always                                   = 1,
	WithHandArmor                            = 2,
	EPenetrateAttenuationType_MAX            = 3,
};

// Enum GPWeaponDefineForPlugin.EWeaponAmmoDamageType
// NumValues: 0x0004
enum class EWeaponAmmoDamageType : uint8
{
	HitFirst                                 = 0,
	PassHand                                 = 1,
	PassHand_IncludeHand                     = 2,
	EWeaponAmmoDamageType_MAX                = 3,
};

// ScriptStruct GPWeaponDefineForPlugin.WeaponIdentity
// 0x0004 (0x0004 - 0x0000)
struct FWeaponIdentity final
{
public:
	uint32                                        UniqueId;                                          // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FWeaponIdentity;

// ScriptStruct GPWeaponDefineForPlugin.GPWeaponHitInfo
// 0x0188 (0x0188 - 0x0000)
struct FGPWeaponHitInfo final
{
public:
	uint8                                         DamageType;                                        // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	uint64                                        FireId;                                            // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FHitResult                             HitResult;                                         // 0x0010(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	uint16                                        BulletIndex;                                       // 0x0098(0x0002)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9A[0x2];                                       // 0x009A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                StartLocation;                                     // 0x009C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                StartDirection;                                    // 0x00A8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FireTime;                                          // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         InWaterTime;                                       // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TWeakObjectPtr<class AActor>                  BulletActor;                                       // 0x00BC(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TWeakObjectPtr<class AActor>                  CharacterOwner;                                    // 0x00C4(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bPenetratedLimbs;                                  // 0x00CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_CD[0x3];                                       // 0x00CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             LimbsHitResult;                                    // 0x00D0(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	TWeakObjectPtr<class AActor>                  HomingTargetActor;                                 // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                RadialLocation;                                    // 0x0160(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_16C[0x4];                                      // 0x016C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         IgnoreActors;                                      // 0x0170(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	uint32                                        VehicleId;                                         // 0x0180(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsInVehicleLeanOut;                               // 0x0184(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_185[0x3];                                      // 0x0185(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGPWeaponHitInfo;

// ScriptStruct GPWeaponDefineForPlugin.FireFromViewConfig
// 0x000C (0x000C - 0x0000)
struct FFireFromViewConfig final
{
public:
	bool                                          bOverrideConfig;                                   // 0x0000(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         TolerantAngle;                                     // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          UseLogicAsBasic;                                   // 0x0008(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FFireFromViewConfig;

// ScriptStruct GPWeaponDefineForPlugin.WeaponHeadDefine
// 0x0001 (0x0001 - 0x0000)
struct FWeaponHeadDefine final
{
public:
	uint8                                         Pad_0[0x1];                                        // 0x0000(0x0001)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FWeaponHeadDefine;

// ScriptStruct GPWeaponDefineForPlugin.WeaponDPVSProxy
// 0x0018 (0x0018 - 0x0000)
struct FWeaponDPVSProxy final
{
public:
	float                                         LastUpdateServerTimeSeconds;                       // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FWeaponIdentity                        WeaponIdentity;                                    // 0x0004(0x0004)(NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector_NetQuantize10                  WeaponActorLocation_RebaseOnZero;                  // 0x0008(0x000C)(NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         WeaponActorRotation_Compressed;                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
};
DUMPER7_ASSERTS_FWeaponDPVSProxy;

// ScriptStruct GPWeaponDefineForPlugin.BulletModeConfig
// 0x0018 (0x0018 - 0x0000)
struct FBulletModeConfig final
{
public:
	bool                                          b1PSpawnBullet;                                    // 0x0000(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MaxPingFor1PSpawnBullet;                           // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          b1PMakeDamage;                                     // 0x0008(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDSSpawnBullet;                                    // 0x0009(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDSMakeDamage;                                     // 0x000A(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bReplicateTo1P;                                    // 0x000B(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bReplicateTo3P;                                    // 0x000C(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableCustomReplication;                          // 0x000D(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_E[0x2];                                        // 0x000E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         NetRelevantDistance;                               // 0x0010(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnablePoolOnDS;                                   // 0x0014(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          b3PSpawnBullet;                                    // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_16[0x2];                                       // 0x0016(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FBulletModeConfig;

// ScriptStruct GPWeaponDefineForPlugin.WeaponFeatureOptions
// 0x0020 (0x0020 - 0x0000)
struct FWeaponFeatureOptions final
{
public:
	bool                                          bShowWeaponMesh;                                   // 0x0000(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bWeaponMeshCastShadow;                             // 0x0001(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableWeaponAnim;                                 // 0x0002(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableCharacterAnim;                              // 0x0003(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableCharacterFireAnim;                          // 0x0004(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableEffect;                                     // 0x0005(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableMuzzleFlashEffect;                          // 0x0006(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableShellDropEffect;                            // 0x0007(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableMuzzleTrailEffect;                          // 0x0008(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableFireAudio;                                  // 0x0009(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableOtherAudio;                                 // 0x000A(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableFireEvent;                                  // 0x000B(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableReloadEvent;                                // 0x000C(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableOtherEvents;                                // 0x000D(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bWeaponSpawnDelay;                                 // 0x000E(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_F[0x1];                                        // 0x000F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         SwitchWeaponRetryInterval;                         // 0x0010(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGPWeaponTickFrequency                        WeaponDataCompAnimTickFrequency;                   // 0x0014(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGPWeaponTickFrequency                        WeaponSkeletalMeshCompTickFrequency;               // 0x0015(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGPWeaponTickFrequency                        WeaponFuncCompAppearanceTickFrequency;             // 0x0016(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGPWeaponTickFrequency                        NormalWeaponPartTickFrequency;                     // 0x0017(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGPWeaponTickFrequency                        HighlightWeaponPartTickFrequency;                  // 0x0018(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LaserAdapterTickInterval;                          // 0x001C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FWeaponFeatureOptions;

// ScriptStruct GPWeaponDefineForPlugin.GPWeaponPenetrateParam
// 0x0014 (0x0014 - 0x0000)
struct FGPWeaponPenetrateParam final
{
public:
	bool                                          bIsValid;                                          // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EWeaponAmmoDamageType                         AmmoDamageType;                                    // 0x0001(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int8                                          AmmoArmorLevelDiff;                                // 0x0002(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPenetrateAttenuationType                     PenetrateAttenuationType;                          // 0x0003(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         PenetrateAttenuationRatio;                         // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int8                                          PenetrateAmmoLevelDecrease;                        // 0x0008(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         PenetrationCoefficient;                            // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bBreakArmor;                                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGPWeaponPenetrateParam;

// ScriptStruct GPWeaponDefineForPlugin.BulletHitRepInfo
// 0x00B0 (0x00B0 - 0x0000)
struct FBulletHitRepInfo
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	uint64                                        BulletGuid;                                        // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint64                                        AmmoId;                                            // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FHitResult                             HitResult;                                         // 0x0018(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	float                                         InitSpeedFor3P;                                    // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAfterRPCOpt;                                      // 0x00A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHitLandScape;                                     // 0x00A5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHitCharacterMesh;                                 // 0x00A6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bClientHitStaticSceneObject;                       // 0x00A7(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bClientHitStaticSceneLandScape;                    // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FBulletHitRepInfo;

// ScriptStruct GPWeaponDefineForPlugin.BulletHitInfo
// 0x0020 (0x00D0 - 0x00B0)
struct FBulletHitInfo final : public FBulletHitRepInfo
{
public:
	uint64                                        BulletIndex;                                       // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                SpawnLocation;                                     // 0x00B8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Timestamp;                                         // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C8[0x8];                                       // 0x00C8(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FBulletHitInfo;

// ScriptStruct GPWeaponDefineForPlugin.PenetratingMediumParam
// 0x0048 (0x0048 - 0x0000)
struct FPenetratingMediumParam final
{
public:
	uint64                                        BulletGuid;                                        // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                BulletVelocity;                                    // 0x0008(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Position;                                          // 0x0014(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                EndPosition;                                       // 0x0020(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C[0xC];                                       // 0x002C(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	TWeakObjectPtr<class AActor>                  Owner;                                             // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_40[0x8];                                       // 0x0040(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FPenetratingMediumParam;

// ScriptStruct GPWeaponDefineForPlugin.BeginFireEventParam
// 0x0010 (0x0010 - 0x0000)
struct FBeginFireEventParam final
{
public:
	uint64                                        FireId;                                            // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LastFireTime;                                      // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FBeginFireEventParam;

// ScriptStruct GPWeaponDefineForPlugin.GPWeaponEventObject
// 0x0001 (0x0001 - 0x0000)
struct FGPWeaponEventObject final
{
public:
	uint8                                         bNoNeedPlayAnim : 1;                               // 0x0000(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
};
DUMPER7_ASSERTS_FGPWeaponEventObject;

// ScriptStruct GPWeaponDefineForPlugin.WeaponBulletMediumInfo
// 0x0014 (0x0014 - 0x0000)
struct FWeaponBulletMediumInfo final
{
public:
	EProjectileMedium                             InitMedium;                                        // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bPenetrateMedium;                                  // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                BorderLoc;                                         // 0x0004(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EProjectileMedium                             NewMedium;                                         // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FWeaponBulletMediumInfo;

// ScriptStruct GPWeaponDefineForPlugin.WeaponFireBulletInfo
// 0x00E8 (0x00E8 - 0x0000)
struct FWeaponFireBulletInfo
{
public:
	uint64                                        BulletGuid;                                        // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint64                                        BulletId;                                          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRotAccurate;                                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector_NetQuantize                    SpawnLocation;                                     // 0x0014(0x000C)(NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               SpawnRotation;                                     // 0x0020(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FRotator                               FireRotation;                                      // 0x002C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FVector                                OwnerVelocity;                                     // 0x0038(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FWeaponBulletMediumInfo                MediumInfo;                                        // 0x0044(0x0014)(NoDestructor, NativeAccessSpecifierPublic)
	class AActor*                                 HomingTarget;                                      // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FHitResult                             PredictHitResult;                                  // 0x0060(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FWeaponFireBulletInfo;

// ScriptStruct GPWeaponDefineForPlugin.WeaponFireOptionalData
// 0x0038 (0x0038 - 0x0000)
struct FWeaponFireOptionalData final
{
public:
	uint8                                         DataOption;                                        // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MovementTimeStamp;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector_NetQuantize100                 CameraLoc;                                         // 0x0008(0x000C)(NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              CameraRot;                                         // 0x0014(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              FireAimRot;                                        // 0x001C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CurrentSeed;                                       // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         KickDeltaTime;                                     // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              KickTargetRot;                                     // 0x002C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Kick_TransRandIndex;                               // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FWeaponFireOptionalData;

// ScriptStruct GPWeaponDefineForPlugin.WeaponFireMulticastInfo
// 0x0078 (0x0078 - 0x0000)
struct FWeaponFireMulticastInfo
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	uint64                                        FireId;                                            // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         BulletIndex;                                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         InitSpeedFor3P;                                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_18[0x8];                                       // 0x0018(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	uint64                                        AmmoId;                                            // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         ComboNumber;                                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FWeaponFireBulletInfo>          BulletInfos;                                       // 0x0030(0x0010)(ZeroConstructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FWeaponFireOptionalData                OptionalData;                                      // 0x0040(0x0038)(NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FWeaponFireMulticastInfo;

// ScriptStruct GPWeaponDefineForPlugin.WeaponFireRepInfo
// 0x0030 (0x00A8 - 0x0078)
struct FWeaponFireRepInfo final : public FWeaponFireMulticastInfo
{
public:
	float                                         InitSpeed;                                         // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        VehicleId;                                         // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsVehicleLeanOut;                                 // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHeavyAttack;                                      // 0x0081(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_82[0x2];                                       // 0x0082(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         FireStateFrameNo;                                  // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FireTimeStamp;                                     // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FTCT;                                              // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ClientLogicFireTimeStamp;                          // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ServerDeltaTime;                                   // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ForceMakeDamageOnDS;                               // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_99[0x3];                                       // 0x0099(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CharacterOwnerLoc;                                 // 0x009C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FWeaponFireRepInfo;

// ScriptStruct GPWeaponDefineForPlugin.GPWeaponAttachInfo
// 0x0040 (0x0040 - 0x0000)
struct FGPWeaponAttachInfo final
{
public:
	EGPWeaponAppearanceAttachType                 AttachType;                                        // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0xF];                                        // 0x0001(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             AttachOffset;                                      // 0x0010(0x0030)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGPWeaponAttachInfo;

// ScriptStruct GPWeaponDefineForPlugin.GPWeaponMesh
// 0x00B0 (0x00B0 - 0x0000)
struct FGPWeaponMesh final
{
public:
	EGPWeaponAppearanceMeshType                   MeshType;                                          // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSoftObjectPath                        MeshObjectPath;                                    // 0x0008(0x0018)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftClassPtr<class UClass>                   MeshAnimClass;                                     // 0x0020(0x0028)(Edit, BlueprintVisible, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnablePhyicals;                                   // 0x0048(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_49[0x3];                                       // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CollisionProfileName;                              // 0x004C(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bNeedBlockBullet;                                  // 0x0054(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_55[0xB];                                       // 0x0055(0x000B)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGPWeaponAttachInfo                    HangBackInfo;                                      // 0x0060(0x0040)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	float                                         HangBackDelaySeconds;                              // 0x00A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         HangFrontDelaySeconds;                             // 0x00A4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A8[0x8];                                       // 0x00A8(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGPWeaponMesh;

// ScriptStruct GPWeaponDefineForPlugin.WeaponMeleeHeavyAttackData
// 0x002C (0x002C - 0x0000)
struct FWeaponMeleeHeavyAttackData final
{
public:
	int32                                         AttackerId;                                        // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackTime;                                        // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackCastTime;                                    // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackBackSwingTime;                               // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackTraceInterval;                               // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackTraceDelay;                                  // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackTraceTime;                                   // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackLockMoveTime;                                // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackRange;                                       // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   AttackAnimSection;                                 // 0x0024(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FWeaponMeleeHeavyAttackData;

// ScriptStruct GPWeaponDefineForPlugin.GPWeaponMeleeComboData
// 0x0040 (0x0040 - 0x0000)
struct FGPWeaponMeleeComboData final
{
public:
	class FName                                   AnimSectionName;                                   // 0x0000(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackTime;                                        // 0x0008(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackCastTime;                                    // 0x000C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackBackSwingTime;                               // 0x0010(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackWaitTime;                                    // 0x0014(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackRange;                                       // 0x0018(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackRadius;                                      // 0x001C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         AttackId;                                          // 0x0020(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SameTimeAttackNumber;                              // 0x0028(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackCastBeforeTime;                              // 0x002C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackCastAfterTime;                               // 0x0030(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackWidth;                                       // 0x0034(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackHeight;                                      // 0x0038(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackForceBreak;                                  // 0x003C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGPWeaponMeleeComboData;

// ScriptStruct GPWeaponDefineForPlugin.GPWeaponPenTrationHitResult
// 0x0090 (0x0090 - 0x0000)
struct alignas(0x04) FGPWeaponPenTrationHitResult final
{
public:
	uint8                                         Pad_0[0x90];                                       // 0x0000(0x0090)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGPWeaponPenTrationHitResult;

// ScriptStruct GPWeaponDefineForPlugin.GPWeaponPenetrationModifier
// 0x000C (0x000C - 0x0000)
struct FGPWeaponPenetrationModifier final
{
public:
	float                                         DamageModifier;                                    // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DistanceModifier;                                  // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StaggerForceModifier;                              // 0x0008(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGPWeaponPenetrationModifier;

// ScriptStruct GPWeaponDefineForPlugin.GPWeaponEventDataBase
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x08) FGPWeaponEventDataBase
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGPWeaponEventDataBase;

// ScriptStruct GPWeaponDefineForPlugin.WeaponEventData_OBPendingBeginFire
// 0x0008 (0x0010 - 0x0008)
struct FWeaponEventData_OBPendingBeginFire final : public FGPWeaponEventDataBase
{
public:
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FWeaponEventData_OBPendingBeginFire;

// ScriptStruct GPWeaponDefineForPlugin.WeaponEventData_TimeOut
// 0x0010 (0x0018 - 0x0008)
struct FWeaponEventData_TimeOut final : public FGPWeaponEventDataBase
{
public:
	float                                         Timeout;                                           // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   NewStateName;                                      // 0x000C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FWeaponEventData_TimeOut;

// ScriptStruct GPWeaponDefineForPlugin.WeaponEventData_ModifyFiringModeType
// 0x0008 (0x0010 - 0x0008)
struct FWeaponEventData_ModifyFiringModeType final : public FGPWeaponEventDataBase
{
public:
	uint8                                         NewFiringModeValue;                                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FWeaponEventData_ModifyFiringModeType;

// ScriptStruct GPWeaponDefineForPlugin.WeaponEventData_InstantHit
// 0x0008 (0x0010 - 0x0008)
struct FWeaponEventData_InstantHit final : public FGPWeaponEventDataBase
{
public:
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FWeaponEventData_InstantHit;

// ScriptStruct GPWeaponDefineForPlugin.WeaponEventData_CancelChangeClip
// 0x0008 (0x0010 - 0x0008)
struct FWeaponEventData_CancelChangeClip final : public FGPWeaponEventDataBase
{
public:
	bool                                          bStop;                                             // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FWeaponEventData_CancelChangeClip;

// ScriptStruct GPWeaponDefineForPlugin.WeaponEventData_DoFire
// 0x0008 (0x0010 - 0x0008)
struct FWeaponEventData_DoFire final : public FGPWeaponEventDataBase
{
public:
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FWeaponEventData_DoFire;

// ScriptStruct GPWeaponDefineForPlugin.WeaponEventData_NotifyBreak
// 0x0008 (0x0010 - 0x0008)
struct FWeaponEventData_NotifyBreak final : public FGPWeaponEventDataBase
{
public:
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FWeaponEventData_NotifyBreak;

// ScriptStruct GPWeaponDefineForPlugin.WeaponEventData_FireModeProxyStateDirty
// 0x0008 (0x0010 - 0x0008)
struct FWeaponEventData_FireModeProxyStateDirty final : public FGPWeaponEventDataBase
{
public:
	bool                                          bWaitingFirstFire;                                 // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bWaitingBurstCD;                                   // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FWeaponEventData_FireModeProxyStateDirty;

// ScriptStruct GPWeaponDefineForPlugin.WeaponEventData_NeedPlayAnim
// 0x0008 (0x0010 - 0x0008)
struct FWeaponEventData_NeedPlayAnim final : public FGPWeaponEventDataBase
{
public:
	uint8                                         bNoNeedPlayAnim : 1;                               // 0x0008(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FWeaponEventData_NeedPlayAnim;

// ScriptStruct GPWeaponDefineForPlugin.WeaponEventData_BeginFire
// 0x0010 (0x0018 - 0x0008)
struct FWeaponEventData_BeginFire final : public FGPWeaponEventDataBase
{
public:
	uint64                                        FireId;                                            // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LastFireTime;                                      // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FWeaponEventData_BeginFire;

}

