#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KantanChartsUMG

#include "Basic.hpp"

#include "KantanChartsSlate_structs.hpp"


namespace SDK
{

// ScriptStruct KantanChartsUMG.SeriesStyleManualMapping
// 0x0028 (0x0028 - 0x0000)
struct FSeriesStyleManualMapping final
{
public:
	class FName                                   SeriesId;                                          // 0x0000(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FKantanSeriesStyle                     Style;                                             // 0x0008(0x0020)(Edit, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSeriesStyleManualMapping;

// ScriptStruct KantanChartsUMG.CategoryStyleManualMapping
// 0x0020 (0x0020 - 0x0000)
struct FCategoryStyleManualMapping final
{
public:
	class FName                                   CategoryId;                                        // 0x0000(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FKantanCategoryStyle                   Style;                                             // 0x0008(0x0018)(Edit, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FCategoryStyleManualMapping;

}

