#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LF_BaseLight_Rect_01

#include "Basic.hpp"

#include "LF_BaseLight_Rect_01_classes.hpp"
#include "LF_BaseLight_Rect_01_parameters.hpp"


namespace SDK
{
}

