#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LF_Lighting_Master

#include "Basic.hpp"

#include "LF_Lighting_Master_classes.hpp"
#include "LF_Lighting_Master_parameters.hpp"


namespace SDK
{
}

