#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LF_Office_TableLamp_01_Warm

#include "Basic.hpp"

#include "LF_Office_TableLamp_01_Warm_classes.hpp"
#include "LF_Office_TableLamp_01_Warm_parameters.hpp"


namespace SDK
{
}

