#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MetaDorian

#include "Basic.hpp"


namespace SDK
{

// Enum MetaDorian.EMTHttpLoaderResult
// NumValues: 0x0004
enum class EMTHttpLoaderResult : uint8
{
	Succeeded                                = 0,
	Failed                                   = 1,
	InvalidURL                               = 2,
	EMTHttpLoaderResult_MAX                  = 3,
};

}

