#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OpenWorldRuntime

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class OpenWorldRuntime.OpenWorldRuntimeUtils
// 0x0000 (0x0028 - 0x0028)
class UOpenWorldRuntimeUtils final : public UBlueprintFunctionLibrary
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OpenWorldRuntimeUtils")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OpenWorldRuntimeUtils")
	}
	static class UOpenWorldRuntimeUtils* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOpenWorldRuntimeUtils>();
	}
};
DUMPER7_ASSERTS_UOpenWorldRuntimeUtils;

// Class OpenWorldRuntime.OpenWorldSettings
// 0x0050 (0x0088 - 0x0038)
class UOpenWorldSettings : public UDeveloperSettings
{
public:
	uint8                                         Pad_38[0x50];                                      // 0x0038(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OpenWorldSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OpenWorldSettings")
	}
	static class UOpenWorldSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOpenWorldSettings>();
	}
};
DUMPER7_ASSERTS_UOpenWorldSettings;

}

