#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SetPlatformStyle

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "EFontConfigData_zh_structs.hpp"


namespace SDK::Params
{

}

