#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SubstanceCore

#include "Basic.hpp"

#include "SubstanceCore_classes.hpp"
#include "SubstanceCore_parameters.hpp"


namespace SDK
{
}

