#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SlotCompName

#include "Basic.hpp"

#include "WBP_SlotCompName_classes.hpp"
#include "WBP_SlotCompName_parameters.hpp"


namespace SDK
{
}

