#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ReorderableListDragArea

#include "Basic.hpp"

#include "GPUserInterfaceCore_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ReorderableListDragArea.WBP_ReorderableListDragArea_C
// 0x0008 (0x0610 - 0x0608)
class UWBP_ReorderableListDragArea_C final : public ULuaUIBaseView
{
public:
	class UNamedSlot*                             NamedSlot_18;                                      // 0x0608(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ReorderableListDragArea_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ReorderableListDragArea_C")
	}
	static class UWBP_ReorderableListDragArea_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ReorderableListDragArea_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ReorderableListDragArea_C;

}

