#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CommonSwitch2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CommonSwitch2.WBP_CommonSwitch2_C
// 0x0040 (0x0330 - 0x02F0)
class UWBP_CommonSwitch2_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UDFCanvasPanel*                         wtCheckboxPanell;                                  // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDFCheckBox*                            wtCheckBoxSwitch;                                  // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TSoftObjectPtr<class UPaperSprite>            ImageIcon;                                         // 0x0308(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_CommonSwitch2(int32 EntryPoint); // (Final, UbergraphFunction) // @ 0x14B5B5E20
	void PreConstruct(bool IsDesignTime); // (BlueprintCosmetic, Event, Public, BlueprintEvent) // @ 0x14B5B5E20

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CommonSwitch2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CommonSwitch2_C")
	}
	static class UWBP_CommonSwitch2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CommonSwitch2_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CommonSwitch2_C;

}

