#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Itemview_Conflict

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Itemview_Conflict.WBP_Itemview_Conflict_C
// 0x0010 (0x0300 - 0x02F0)
class UWBP_Itemview_Conflict_C final : public UUserWidget
{
public:
	class UDFImage*                               DFImage_73;                                        // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_26;                                          // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Itemview_Conflict_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Itemview_Conflict_C")
	}
	static class UWBP_Itemview_Conflict_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Itemview_Conflict_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Itemview_Conflict_C;

}

