#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RoleInfo_Detail_TittleText

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_RoleInfo_Detail_TittleText.WBP_RoleInfo_Detail_TittleText_C
// 0x0030 (0x0320 - 0x02F0)
class UWBP_RoleInfo_Detail_TittleText_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UDFTextBlock*                           DFTextBlock01_Num;                                 // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDFTextBlock*                           DFTextBlock01_Tittle;                              // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   Text;                                              // 0x0308(0x0018)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_WBP_RoleInfo_Detail_TittleText(int32 EntryPoint); // (Final, UbergraphFunction) // @ 0x14B5B5E20
	void PreConstruct(bool IsDesignTime); // (BlueprintCosmetic, Event, Public, BlueprintEvent) // @ 0x14B5B5E20

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_RoleInfo_Detail_TittleText_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_RoleInfo_Detail_TittleText_C")
	}
	static class UWBP_RoleInfo_Detail_TittleText_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_RoleInfo_Detail_TittleText_C>();
	}
};
DUMPER7_ASSERTS_UWBP_RoleInfo_Detail_TittleText_C;

}

