#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SetUpComponent_SplitBtn_2

#include "Basic.hpp"

#include "WBP_SetUpComponent_SplitBtn_2_classes.hpp"
#include "WBP_SetUpComponent_SplitBtn_2_parameters.hpp"


namespace SDK
{
}

