#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_VehiclesMainV2_Item

#include "Basic.hpp"

#include "WBP_VehiclesMainV2_Item_classes.hpp"
#include "WBP_VehiclesMainV2_Item_parameters.hpp"


namespace SDK
{
}

