#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CommonReconnectLoading

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GPUserInterfaceCore_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CommonReconnectLoading.WBP_CommonReconnectLoading_C
// 0x0020 (0x0628 - 0x0608)
class UWBP_CommonReconnectLoading_C final : public ULuaUIBaseView
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0608(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       WBP_CommonReconnectLoading_Loop;                   // 0x0610(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UDFCanvasPanel*                         DFCanvasPanel_46;                                  // 0x0618(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDFTextBlock*                           DFTextBlock_40;                                    // 0x0620(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_CommonReconnectLoading(int32 EntryPoint); // (Final, UbergraphFunction) // @ 0x14B5B5E20
	void PreConstruct(bool IsDesignTime); // (BlueprintCosmetic, Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void Construct(); // (BlueprintCosmetic, Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void SetStyle(); // (Public, HasDefaults, BlueprintCallable, BlueprintEvent) // @ 0x14B5B5E20

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CommonReconnectLoading_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CommonReconnectLoading_C")
	}
	static class UWBP_CommonReconnectLoading_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CommonReconnectLoading_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CommonReconnectLoading_C;

}

