#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DFCommonButtonV1S2

#include "Basic.hpp"

#include "WBP_DFCommonButtonV1S2_classes.hpp"
#include "WBP_DFCommonButtonV1S2_parameters.hpp"


namespace SDK
{
}

