#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CommonButtonV1S1

#include "Basic.hpp"

#include "WBP_CommonButtonV1S1_classes.hpp"
#include "WBP_CommonButtonV1S1_parameters.hpp"


namespace SDK
{
}

