#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Marker_Map_EdgaTrackingBigMap

#include "Basic.hpp"

#include "DFMGameHud_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Marker_Map_EdgaTrackingBigMap.WBP_Marker_Map_EdgaTrackingBigMap_C
// 0x0000 (0x0308 - 0x0308)
class UWBP_Marker_Map_EdgaTrackingBigMap_C final : public UEdgeTrackingWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Marker_Map_EdgaTrackingBigMap_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Marker_Map_EdgaTrackingBigMap_C")
	}
	static class UWBP_Marker_Map_EdgaTrackingBigMap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Marker_Map_EdgaTrackingBigMap_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Marker_Map_EdgaTrackingBigMap_C;

}

