#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Skill_NightVision_Low

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Skill_NightVision_Low.WBP_Skill_NightVision_Low_C
// 0x0018 (0x0308 - 0x02F0)
class UWBP_Skill_NightVision_Low_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCanvasPanel*                           CanvasPanel_NightVision;                           // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUIMeshWidget*                          UIMeshWidget_Nightversion;                         // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_Skill_NightVision_Low(int32 EntryPoint); // (Final, UbergraphFunction) // @ 0x14B5B5E20
	void PreConstruct(bool IsDesignTime); // (BlueprintCosmetic, Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void Construct(); // (BlueprintCosmetic, Event, Public, BlueprintEvent) // @ 0x14B5B5E20
	void SetImage(TSoftObjectPtr<class UTexture2D> ImageType); // (Public, HasDefaults, BlueprintCallable, BlueprintEvent) // @ 0x14B5B5E20

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Skill_NightVision_Low_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Skill_NightVision_Low_C")
	}
	static class UWBP_Skill_NightVision_Low_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Skill_NightVision_Low_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Skill_NightVision_Low_C;

}

