#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WeaponStateInteractionBegin

#include "Basic.hpp"

#include "GPWeaponRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WeaponStateInteractionBegin.WeaponStateInteractionBegin_C
// 0x0000 (0x00A8 - 0x00A8)
class UWeaponStateInteractionBegin_C final : public UGPWeaponFSMStateBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WeaponStateInteractionBegin_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WeaponStateInteractionBegin_C")
	}
	static class UWeaponStateInteractionBegin_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWeaponStateInteractionBegin_C>();
	}
};
DUMPER7_ASSERTS_UWeaponStateInteractionBegin_C;

}

