#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WeaponPhysicsBulletReal_BP_3P

#include "Basic.hpp"

#include "GPGameplay_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WeaponPhysicsBulletReal_BP_3P.WeaponPhysicsBulletReal_BP_3p_C
// 0x0010 (0x0CB0 - 0x0CA0)
class AWeaponPhysicsBulletReal_BP_3p_C final : public AWeaponBulletPhysicsSimulate
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0CA0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WeaponPhysicsBulletReal_BP_3p_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WeaponPhysicsBulletReal_BP_3p_C")
	}
	static class AWeaponPhysicsBulletReal_BP_3p_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeaponPhysicsBulletReal_BP_3p_C>();
	}
};
DUMPER7_ASSERTS_AWeaponPhysicsBulletReal_BP_3p_C;

}

