#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: XeSS2Blueprint

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "XeSS2Blueprint_structs.hpp"


namespace SDK::Params
{

}

